Ik/move cli tests
open-edge-platform/training_extensions pull request #1006
Opened 2022-03-24 10:44 UTC by Ilya-Krylov

2022-03-24 10:44 UTC, Ilya-Krylov commented
run ote-test

2022-03-24 10:44 UTC, Ilya-Krylov commented
run ote_sdk tests

2022-03-24 11:08 UTC, Ilya-Krylov commented
run ote_sdk tests

2022-03-24 12:37 UTC, Ilya-Krylov commented
run ote_sdk tests

2022-03-24 19:46 UTC, Ilya-Krylov commented
run ote_sdk tests

2022-03-24 19:47 UTC, Ilya-Krylov commented
run ote-test

2022-03-24 19:55 UTC, Ilya-Krylov commented
run ote_sdk tests

2022-03-24 19:55 UTC, Ilya-Krylov commented
run ote-test

2022-03-25 06:56 UTC, Ilya-Krylov commented
run ote_sdk tests

2022-03-25 06:56 UTC, Ilya-Krylov commented
run ote-test

2022-03-25 07:06 UTC, LeonidBeynenson commented on external/anomaly/init_venv.sh
> +pip install -e ../../ote_sdk/ || exit 1
Ilya, sorry, do not use relative paths

2022-03-25 07:07 UTC, LeonidBeynenson requested changes

2022-03-25 07:07 UTC, LeonidBeynenson commented on external/anomaly/init_venv.sh
>  pip install -e .
Ilya, please, insert `|| exit 1` here

2022-03-25 07:11 UTC, Ilya-Krylov commented on external/anomaly/init_venv.sh
>  pip install -e .
fixed

2022-03-25 07:56 UTC, Ilya-Krylov commented
run ote-test

2022-03-25 08:36 UTC, merged