[Anomaly Task] Fix non deterministic + sample.py
open-edge-platform/training_extensions pull request #1118
Opened 2022-05-23 13:43 UTC by ashwinvaidya17

# Changes

- Fix doc string in sample.py
- Add seed to train task. The only issue here is that I am not sure how the tests are run. They might not use seed. This is also the second issue. It changes the function signature which might not be a good idea.
- I've added a small readme to tools folder regarding sample.py. I feel these two commands are enough but let me know if you need anything else.

2022-05-23 13:52 UTC, samet-akcay commented on external/anomaly/tools/README.md
> +```
Can you split the line here

```
python tools/sample.py \
    --dataset_path ~/datasets/MVTec \
    --category bottle \
    --train-ann-files ../../data/MVtec/bottle/segmentation/train.json \
    --val-ann-files ../../data/MVtec/bottle/segmentation/val.json \
    --test-ann-files ../../data/MVtec/bottle/segmentation/test.json \
    --model_template_path ./configs/anomaly_segmentation/padim/template.yaml
```

2022-05-23 13:52 UTC, samet-akcay commented on external/anomaly/tools/sample.py
> +        seed: Optional[int] = 0,
If the variable `Optional`, shouldn't it be set to `None`?

2022-05-23 13:53 UTC, samet-akcay commented on external/anomaly/ote_anomalib/train_task.py
> +        seed: Optional[int] = 0,
If the variable `Optional`, shouldn't it be set to `None`?

2022-05-23 13:54 UTC, samet-akcay requested changes
Thanks for creating this PR, only minor comments

2022-05-24 06:53 UTC, ashwinvaidya17 commented
Anomaly tests have passed but looks like deep-object-reid and mmsegmentation tests are failing

2022-05-31 06:45 UTC, goodsong81 approved these changes
LGTM

2022-05-31 06:45 UTC, merged