[ANOMALY] Use is_anomalous attribute instead of string matching
open-edge-platform/training_extensions pull request #1120
Opened 2022-05-24 15:59 UTC by djdameln

The exportable code used string matching to check the normal/anomalous labels based on the label name. This is not safe, because in a future version the label names in anomaly projects may be customizable. This PR replaces the string matching with a check based on the is_anomalous attribute of the label entity.

2022-05-24 16:01 UTC, samet-akcay approved these changes, later dismissed
Thanks!

2022-05-24 17:59 UTC, ashwinvaidya17 submitted a review, later dismissed
Thanks for updating it!

2022-05-25 06:41 UTC, goodsong81 commented
run ote-test

2022-05-27 08:32 UTC, goodsong81 requested changes
There are bunch of errors regarding this change. For example,
![image](https://user-images.githubusercontent.com/4629606/170662451-0e3234e1-bbff-43ef-966f-40c47a9e048f.png)

Please look into https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/316/ and fix test failures.

2022-05-30 09:35 UTC, djdameln commented
run ote-test

2022-05-30 09:37 UTC, djdameln commented
> There are bunch of errors regarding this change. For example, ![image](https://user-images.githubusercontent.com/4629606/170662451-0e3234e1-bbff-43ef-966f-40c47a9e048f.png)
> 
> Please look into https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/316/ and fix test failures.

I had to update the test cases, which were not setting the is_anomalous attribute correctly when creating the labels. Should be good now.

2022-05-31 06:40 UTC, goodsong81 approved these changes

2022-05-31 06:40 UTC, merged