Add label source to scored label
open-edge-platform/training_extensions pull request #1138
Opened 2022-06-15 23:18 UTC by JortBergfeld

2022-06-16 08:54 UTC, leoll2 commented
run ote-test

2022-06-16 09:00 UTC, leoll2 commented on ote_sdk/ote_sdk/entities/scored_label.py
> +    set at a later stage.
This comment doesn't fit here imho, the low-level SDK entities should be unaware of the application code that uses them.

2022-06-16 09:18 UTC, leoll2 reviewed
LGTM, waiting for tests before approving.
Some questions:
- Who is responsible for updating the `label_source` value? OTE, SC or both?
- Have you considered the possibility of implementing this information in SC only, not OTE? Afaik, it's not strictly needed by OTE, and fields like "user" are a bit out of context in OTE. On the other hand, if OTE creates the predictions, it's more efficient to set the right value there rather than later in SC.

2022-06-17 07:38 UTC, JortBergfeld commented
> LGTM, waiting for tests before approving. Some questions:
> 
>     * Who is responsible for updating the `label_source` value? OTE, SC or both?
> 
>     * Have you considered the possibility of implementing this information in SC only, not OTE? Afaik, it's not strictly needed by OTE, and fields like "user" are a bit out of context in OTE. On the other hand, if OTE creates the predictions, it's more efficient to set the right value there rather than later in SC.

@leoll2 SC is indeed responsible for setting this information and we have considered putting the LabelSource in SC, but due to how we set up the code of the SDK and SC, it is no longer possible to properly add it to the SC code without a redesign of the SDK's. AnnotationScene (SC) inherits from AnnotationSceneEntity (OTE), which has a list of Annotations (OTE), which has a list of ScoredLabels (OTE), therefore adding LabelSource info to/about the ScoredLabel and making sure all methods properly deal with it is hard without adding it to the OTE_SDK. We have discussed the possible solutions for this problem, but all of them require a huge refactoring. We still want to do this, more generally move all information that OTE does not need to SC, but we will make a separate ticket/epic for that.

2022-06-17 07:44 UTC, leoll2 submitted a review, later dismissed
Thanks for the detailed explanation, now I see the problem. Hopefully in the future we will decouple the two SDKs in a better fashion.

2022-06-17 12:11 UTC, AlbertvanHouten approved these changes, later dismissed

2022-06-17 12:14 UTC, leoll2 submitted a review, later dismissed

2022-06-21 08:18 UTC, JortBergfeld commented
run ote-test

2022-06-21 08:51 UTC, atwinand approved these changes, later dismissed
LGTM!

2022-06-22 07:23 UTC, goodsong81 requested changes
There seems to be some test failures regarding this change.
Could you resolve them or confirm they are not related to this PR?
Build: https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/393/
Failures:
- http://validationreports.sclab.intel.com:8006/reports/test_result/62b1a18c83a7dafed5ece8ee
- http://validationreports.sclab.intel.com:8006/reports/test_result/62b1a19283a7dafed5ecea0a

2022-06-23 00:49 UTC, goodsong81 commented
run ote-test

2022-06-24 06:48 UTC, leoll2 approved these changes

2022-06-24 06:57 UTC, AlbertvanHouten approved these changes

2022-06-27 08:33 UTC, goodsong81 approved these changes
LGTM.

2022-06-27 08:33 UTC, merged