Yc/cvs 84805 update for adaptive free asha
open-edge-platform/training_extensions pull request #1143
Opened 2022-06-22 04:31 UTC by yunchu

updated for HPO

- to apply hpopt updates, some required part in the OTE was updated
- enabled hpo to new tasks
    * object counting
    * rotated boundbox detection
    * anomaly tasks

2022-06-22 04:58 UTC, yunchu commented
run ote-test

2022-06-28 01:15 UTC, yunchu commented
run ote-test

2022-06-28 05:12 UTC, yunchu commented
run ote-test

2022-06-28 05:53 UTC, yunchu commented
run ote-test

2022-06-28 06:18 UTC, yunchu commented
run ote-test

2022-06-28 06:30 UTC, yunchu commented
run ote-test

2022-06-29 02:57 UTC, yunchu commented
test completed with some failures but those are not related with this PR.
http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=pr-ote-test-413&environment=iotg-dev-workstation-18

2022-06-29 06:50 UTC, goodsong81 approved these changes, later dismissed
LGTM.
Please note that MPA templates would also need similar changes after a while.

2022-06-29 06:59 UTC, harimkang submitted a review, later dismissed
LGTM

2022-07-01 00:49 UTC, eunwoosh requested changes

2022-07-01 00:49 UTC, eunwoosh commented on external/mmdetection/detection_tasks/extension/utils/hooks.py
> +        runner.log_buffer.output['current_iters'] = runner.iter
Doesn't this code need to be only in after_epoch function?

2022-07-01 00:49 UTC, eunwoosh commented on external/mmsegmentation/segmentation_tasks/extension/utils/hooks.py
> +        runner.log_buffer.output['current_iters'] = runner.iter
It's the same question as above, doesn't this code need to be only in after_epoch function?

2022-07-01 00:49 UTC, eunwoosh commented on ote_cli/ote_cli/utils/hpo.py
> +
Doesn't code to process the case where "min_iteration" ig bigger than "max_iteration" need to be here?

2022-07-01 00:49 UTC, eunwoosh commented on ote_cli/ote_cli/utils/hpo.py
> +        #     best_config["learning_parameters.learning_rate_warmup_iters"] = 0
It looks better to move these codes in HpoTrainTask class in get_train_wrapper_task function.
How do you think about?

2022-07-01 00:49 UTC, eunwoosh commented on ote_cli/ote_cli/utils/hpo.py
> +        self.deleted_hp = {}
I think this variable name is confusing. I'll change this name to decided_hp.

2022-07-01 00:49 UTC, eunwoosh commented on ote_cli/ote_cli/utils/hpo.py
> +        self.deleted_hp = {}
I changed it to fixed_hp and add comments

2022-07-01 00:52 UTC, yunchu commented on external/mmdetection/detection_tasks/extension/utils/hooks.py
> +        runner.log_buffer.output['current_iters'] = runner.iter
what we want to get for the HPO callback is now iteration number. so we can only put it on this event.

2022-07-01 00:55 UTC, yunchu commented on ote_cli/ote_cli/utils/hpo.py
> +
we've already put the defense code for that case in the hpopt module. so i don't think it should be here again.

2022-07-01 00:57 UTC, yunchu commented on ote_cli/ote_cli/utils/hpo.py
> +        #     best_config["learning_parameters.learning_rate_warmup_iters"] = 0
those codes are commented out so can you point out again correctly what "these codes" mean?

2022-07-01 03:36 UTC, eunwoosh commented on ote_cli/ote_cli/utils/hpo.py
> +        #     best_config["learning_parameters.learning_rate_warmup_iters"] = 0
I meant to move code commented out in HpoTrainTask class. But I think it's better to implement this part in each OTE tasks.

2022-07-01 03:38 UTC, eunwoosh approved these changes, later dismissed

2022-07-01 04:42 UTC, eunwoosh approved these changes

2022-07-01 05:00 UTC, goodsong81 approved these changes

2022-07-01 05:15 UTC, merged