[Detection] enable saliency map detection
open-edge-platform/training_extensions pull request #1155
Opened 2022-07-06 14:58 UTC by eugene123tw

Correponded ticket for MPA: https://github.com/openvinotoolkit/model_preparation_algorithm/pull/24

2022-07-07 16:36 UTC, eugene123tw commented
run ote-test

2022-07-12 10:58 UTC, eugene123tw commented
run ote-test

2022-07-12 11:05 UTC, eugene123tw commented
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/434/

2022-07-12 11:07 UTC, eugene123tw commented
run ote-test

2022-07-12 11:11 UTC, eugene123tw commented
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/435/

2022-07-12 15:25 UTC, JihwanEom submitted a review, later dismissed
LGTM.

2022-07-12 15:25 UTC, JihwanEom commented on external/model-preparation-algorithm/mpa_tasks/apis/detection/task.py
> +            dataset (DatasetEntity): the valuation or test dataset to be inferred with
typo for valuation -> validation?

2022-07-13 00:54 UTC, harimkang requested changes
The code contents seem to be clear. But the change in the submodule seems a little strange, is it right for the develop branch? It seems necessary to match the submodule commit.

2022-07-13 04:11 UTC, harimkang submitted a review, later dismissed
I was mistaken about the comment above. I mistook both the ote and mpa for develop branch.
LGTM

2022-07-13 07:07 UTC, harimkang commented
Pretty big PR just got merged. Please correct the MPA submodule (develop branch) and MPA task as part of it has been changed.

2022-07-13 11:00 UTC, eugene123tw commented
run ote-test

2022-07-13 11:02 UTC, eugene123tw commented
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/436/

2022-07-13 11:03 UTC, eugene123tw commented
@harimkang Thanks for the review. I have merged the latest commit from develop branch

2022-07-13 12:18 UTC, harimkang approved these changes
LGTM

2022-07-15 06:29 UTC, chuneuny-emily approved these changes

2022-07-15 06:29 UTC, goodsong81 approved these changes

2022-07-15 06:32 UTC, merged