Add no show flag to visualizer in exportable code
open-edge-platform/training_extensions pull request #1204
Opened 2022-08-09 14:08 UTC by sovrasov

2022-08-09 14:09 UTC, sovrasov commented
run ote-test

2022-08-10 08:34 UTC, sovrasov commented
Build # 509, see \*exportable_code\* test cases.

2022-08-10 08:54 UTC, sovrasov commented
run ote-test

2022-08-11 12:20 UTC, sovrasov commented
run ote-test

2022-08-12 16:40 UTC, sovrasov commented
run ote-test

2022-08-17 12:05 UTC, sovrasov commented
run ote-test

2022-08-18 13:46 UTC, sovrasov commented
@goodsong81 @eugene123tw I found the reason why openvino_deploy tests are failing: these tests use a fixed commit of [ote_sdk](https://github.com/openvinotoolkit/training_extensions/blob/develop/ote_sdk/ote_sdk/usecases/exportable_code/demo/requirements.txt). I propose to merge this PR first and then update the ote commit in requirements in a standalone PR. This allows to avoid mentioning intermediate SDK commits. As a second option I can use the latest commit from the current branch, then I don't need to create one more PR.

2022-08-18 14:43 UTC, eugene123tw commented
> 

I think it's fine if we update OTE commit in this PR.

2022-08-18 16:31 UTC, sovrasov commented
run ote-test

2022-08-19 08:25 UTC, sovrasov commented
Tests are passed [#PR1204-534-test]

2022-08-19 08:42 UTC, goodsong81 approved these changes, later dismissed
LGTM

2022-08-22 11:07 UTC, sovrasov commented
@eugene123tw could you have a look?

2022-08-23 09:00 UTC, eugene123tw requested changes

2022-08-23 09:00 UTC, eugene123tw commented on ote_sdk/ote_sdk/usecases/exportable_code/demo/demo.py
> +        "--no_show",
Hi Vlad, the code looks good to me, that said, I have a few minor change requests
* Could we change `--no_show` to `--no-show`?

Regarding README: https://github.com/openvinotoolkit/training_extensions/blob/develop/ote_sdk/ote_sdk/usecases/exportable_code/demo/README.md
* Add descriptions for the new flag `--no-show`
* Change `<path_to_model>` to `<path_to_model_directory>`

2022-08-23 09:00 UTC, eugene123tw commented on ote_sdk/ote_sdk/usecases/exportable_code/visualizers/visualizer.py
> +        return ord("q") == cv2.waitKey(self.delay)
@sovrasov LGTM. Could you add a newline here?

2022-08-23 09:19 UTC, eugene123tw approved these changes, later dismissed
LGTM

2022-08-23 09:25 UTC, sovrasov commented
@goodsong81 could you merge?

2022-08-23 09:38 UTC, goodsong81 approved these changes, later dismissed
LGTM. BTW, does this PR need to be included SC release?
Then please redirect to releases/v0.3.0-sc1.2 branch.

2022-08-23 09:40 UTC, sovrasov commented
This PR could be included indeed, I'll try to redirect then, if there are no conflicts

2022-08-23 09:40 UTC, samet-akcay commented
> LGTM. BTW, does this PR need to be included SC release?
Then please redirect to releases/v0.3.0-sc1.2 branch.

Also another PR to the [otx branch](https://github.com/openvinotoolkit/training_extensions/tree/feature/otx) please

2022-08-23 09:41 UTC, sovrasov commented
@goodsong81 I've changed the base branch, there are no conflicts

2022-08-23 09:59 UTC, goodsong81 approved these changes

2022-08-24 08:07 UTC, eugene123tw approved these changes
LGTM

2022-08-24 08:09 UTC, merged