[CVS-94911] Fix difference between train and validation normalization pipeline
open-edge-platform/training_extensions pull request #1310
Opened 2022-10-24 08:14 UTC by jaegukhyun

This PR includes solve issue CVS-94911.
Previous implementation only look into pipeline of the most inside dataset
I change the code to also look into outside dataset
I think we should refactor this function recursive way to handle various dataset settings.

2022-10-24 10:12 UTC, goodsong81 reviewed
Could you replicate this change to feature/otx?
@harimkang Or, do you have plan to move changes to develop to feature/otx?

2022-10-25 00:07 UTC, harimkang commented
> Could you replicate this change to feature/otx? @harimkang Or, do you have plan to move changes to develop to feature/otx?

Commits with (& after) tiling are not included in `feature/otx`. However, I know that `develop` currently has some issues. When those issues are resolved, I will reflect `develop` to `feature/otx` once.

2022-10-25 02:02 UTC, jaegukhyun commented
> Could you replicate this change to feature/otx?

I can directly change otx/feature branch to reflect this PR. However if there are plan to merge develop and otx/feature branch, then I can wait for it.

2022-10-25 02:43 UTC, sungchul2 commented
I checked all of `to_rgb` are changed to `False`.
If modified parts are fine, you can merge it.

2022-10-25 02:45 UTC, sungchul2 approved these changes, later dismissed

2022-10-27 16:37 UTC, eugene123tw commented
run ote-test

2022-10-28 18:22 UTC, eugene123tw requested changes
I'm getting this error running tests. Could you take a look?

```
Traceback (most recent call last):
  File "/tmp/ote_cli/model-preparation-algorithm/venv/bin/ote", line 33, in <module>
    sys.exit(load_entry_point('ote-cli', 'console_scripts', 'ote')())
  File "/home/yuchunli/git/training_extensions/ote_cli/ote_cli/tools/ote.py", line 67, in main
    globals()[f"ote_{name}"]()
  File "/home/yuchunli/git/training_extensions/ote_cli/ote_cli/tools/train.py", line 175, in main
    task.train(dataset, output_model, train_parameters=TrainParameters())
  File "/home/yuchunli/git/training_extensions/external/model-preparation-algorithm/mpa_tasks/apis/detection/task.py", line 528, in train
    results = self._run_task(stage_module, mode="train", dataset=dataset, parameters=train_parameters)
  File "/home/yuchunli/git/training_extensions/external/model-preparation-algorithm/mpa_tasks/apis/task.py", line 112, in _run_task
    output = workflow.run(
  File "/home/yuchunli/git/training_extensions/external/model-preparation-algorithm/submodule/mpa/det/trainer.py", line 126, in run
    DetectionTrainer.train_worker(
  File "/home/yuchunli/git/training_extensions/external/model-preparation-algorithm/submodule/mpa/det/trainer.py", line 161, in train_worker
    train_detector(
  File "/home/yuchunli/git/training_extensions/external/mmdetection/submodule/mmdet/apis/train.py", line 260, in train_detector
    runner.run(data_loaders, cfg.workflow, compression_ctrl=compression_ctrl)
  File "/tmp/ote_cli/model-preparation-algorithm/venv/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/yuchunli/git/training_extensions/ote_sdk/ote_sdk/utils/argument_checks.py", line 250, in validate
    return function(**input_parameters_values_map)
  File "/home/yuchunli/git/training_extensions/external/model-preparation-algorithm/mpa_tasks/utils/runner.py", line 53, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/tmp/ote_cli/model-preparation-algorithm/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/tmp/ote_cli/model-preparation-algorithm/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/tmp/ote_cli/model-preparation-algorithm/venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/tmp/ote_cli/model-preparation-algorithm/venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yuchunli/git/training_extensions/external/mmdetection/submodule/mmdet/datasets/dataset_wrappers.py", line 475, in __getitem__
    return self.pipeline(self.tile_dataset[idx])
  File "/home/yuchunli/git/training_extensions/external/mmdetection/submodule/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/home/yuchunli/git/training_extensions/external/mmdetection/submodule/mmdet/datasets/pipelines/formating.py", line 322, in __call__
    img_meta[key] = results[key]
KeyError: 'ignored_labels'
FAILED
```

2022-10-31 00:24 UTC, harimkang commented on external/model-preparation-algorithm/mpa_tasks/apis/detection/task.py
> +                        pipeline_step = BaseTask._get_meta_keys(pipeline_step)
The `ignored_labels` key error in the comment is a problem that can be solved by going through this `_get_meta_keys` function. I can't seem to get into this line, so please check.

2022-10-31 04:59 UTC, harimkang commented
> I'm getting this error running tests. Could you take a look?
> 
> ```
> Traceback (most recent call last):
>   File "/tmp/ote_cli/model-preparation-algorithm/venv/bin/ote", line 33, in <module>
>     sys.exit(load_entry_point('ote-cli', 'console_scripts', 'ote')())
>   File "/home/yuchunli/git/training_extensions/ote_cli/ote_cli/tools/ote.py", line 67, in main
>     globals()[f"ote_{name}"]()
>   File "/home/yuchunli/git/training_extensions/ote_cli/ote_cli/tools/train.py", line 175, in main
>     task.train(dataset, output_model, train_parameters=TrainParameters())
>   File "/home/yuchunli/git/training_extensions/external/model-preparation-algorithm/mpa_tasks/apis/detection/task.py", line 528, in train
>     results = self._run_task(stage_module, mode="train", dataset=dataset, parameters=train_parameters)
>   File "/home/yuchunli/git/training_extensions/external/model-preparation-algorithm/mpa_tasks/apis/task.py", line 112, in _run_task
>     output = workflow.run(
>   File "/home/yuchunli/git/training_extensions/external/model-preparation-algorithm/submodule/mpa/det/trainer.py", line 126, in run
>     DetectionTrainer.train_worker(
>   File "/home/yuchunli/git/training_extensions/external/model-preparation-algorithm/submodule/mpa/det/trainer.py", line 161, in train_worker
>     train_detector(
>   File "/home/yuchunli/git/training_extensions/external/mmdetection/submodule/mmdet/apis/train.py", line 260, in train_detector
>     runner.run(data_loaders, cfg.workflow, compression_ctrl=compression_ctrl)
>   File "/tmp/ote_cli/model-preparation-algorithm/venv/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
>     epoch_runner(data_loaders[i], **kwargs)
>   File "/home/yuchunli/git/training_extensions/ote_sdk/ote_sdk/utils/argument_checks.py", line 250, in validate
>     return function(**input_parameters_values_map)
>   File "/home/yuchunli/git/training_extensions/external/model-preparation-algorithm/mpa_tasks/utils/runner.py", line 53, in train
>     for i, data_batch in enumerate(self.data_loader):
>   File "/tmp/ote_cli/model-preparation-algorithm/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
>     data = self._next_data()
>   File "/tmp/ote_cli/model-preparation-algorithm/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
>     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
>   File "/tmp/ote_cli/model-preparation-algorithm/venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/tmp/ote_cli/model-preparation-algorithm/venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/home/yuchunli/git/training_extensions/external/mmdetection/submodule/mmdet/datasets/dataset_wrappers.py", line 475, in __getitem__
>     return self.pipeline(self.tile_dataset[idx])
>   File "/home/yuchunli/git/training_extensions/external/mmdetection/submodule/mmdet/datasets/pipelines/compose.py", line 40, in __call__
>     data = t(data)
>   File "/home/yuchunli/git/training_extensions/external/mmdetection/submodule/mmdet/datasets/pipelines/formating.py", line 322, in __call__
>     img_meta[key] = results[key]
> KeyError: 'ignored_labels'
> FAILED
> ```

Hi @eugene123tw, I talked about this with @jaegukhyun . Currently, other datasets in OTX are able to receive ignored_labels as collection inputs, but the tiling dataset seems to be an issue because it is not handled that way. Once it is tiling, Jaeguk will fix it so that the function is not called. It would be nice to be able to receive `ignored_labels` from the tiling dataset in the future. For now, let's fix it as a temporary solution.

2022-10-31 07:47 UTC, jaegukhyun commented
run ote-test

2022-11-08 05:54 UTC, jaegukhyun commented
run ote-test

2022-11-09 01:03 UTC, jaegukhyun commented
run ote-test

2022-11-09 01:09 UTC, jaegukhyun commented
run ote-test

2022-11-10 01:28 UTC, jaegukhyun commented
http://validationreports.sclab.intel.com:8006/reports/build_number_report?trimReq=on&status=FAIL&test_session_build_number=pr-ote-test-697&environment=iotg-dev-workstation-09
@harimkang, @eugene123tw It's time to merge this PR, could you check this once more?

2022-11-22 11:11 UTC, eugene123tw approved these changes

2022-11-23 04:24 UTC, harimkang approved these changes

2022-11-23 04:25 UTC, merged