[Develop] Move drop_last into MPA
open-edge-platform/training_extensions pull request #1357
Opened 2022-11-10 07:42 UTC by JihwanEom

## Related Issues
- https://jira.devtools.intel.com/browse/CVS-96224

Related MPA PR: https://github.com/openvinotoolkit/model_preparation_algorithm/pull/79

2022-11-10 08:43 UTC, JihwanEom commented
run ote-test

2022-11-11 01:43 UTC, goodsong81 requested changes
Check submodules. This PR includes irrelevant changes.

2022-11-11 01:50 UTC, goodsong81 approved these changes

2022-11-11 02:11 UTC, sungmanc approved these changes
LGTM

2022-11-11 02:14 UTC, merged