Enable tiling oriented detection for v0.4.0/geti1.1.0
open-edge-platform/training_extensions pull request #1427
Opened 2022-12-08 12:29 UTC by eugene123tw

2022-12-08 12:30 UTC, eugene123tw commented
run ote-test

2022-12-08 12:33 UTC, eugene123tw commented
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/826/

2022-12-09 00:36 UTC, harimkang commented on ote_sdk/ote_sdk/usecases/exportable_code/demo/demo_package/model_container.py
> +            predictions = detection2array(predictions)
As I analyzed yesterday, Classification also passes through the code and causes an issue here. It seems to me that this code only filters out segmentation, is that correct?

2022-12-09 00:37 UTC, harimkang commented on external/model-preparation-algorithm/configs/rotated-detection/efficientnetb2b_maskrcnn/data_pipeline.py
> +img_norm_cfg = dict(mean=(103.53, 116.28, 123.675), std=(1.0, 1.0, 1.0), to_rgb=True)
@jaegukhyun Could you please comment on this? Any problem?

2022-12-09 00:49 UTC, harimkang commented
> https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/826/

As confirmed with this build, there are still issues with classification and segmentation.

2022-12-09 02:30 UTC, goodsong81 commented on ote_sdk/ote_sdk/usecases/exportable_code/demo/demo_package/model_container.py
> +        if not self.segm:
```suggestion
        if self._task_type == TaskType.DETECTION:
```

If I'm correctly understanding, detection2array() is only for detection task.

2022-12-09 02:46 UTC, goodsong81 requested changes
Need to resolve test failures.

2022-12-09 03:35 UTC, harimkang commented
run ote-test

2022-12-09 03:38 UTC, harimkang commented
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/828/

2022-12-09 07:28 UTC, goodsong81 commented
Geti enabling test (for reference): https://ci.iotg.sclab.intel.com/job/IMPT/job/IMPTOps/48653/

2022-12-09 09:07 UTC, harimkang approved these changes
![image](https://user-images.githubusercontent.com/38045080/206665531-61c644c6-2990-402f-aeab-691f6b022555.png)
all passed ote cli's mpa test in my local

2022-12-09 21:10 UTC, eugene123tw commented
Passed: 1170 (88.77%)
Ignored: 147 (11.15%)
Failed: 1 (0.08%)


@harimkang @goodsong81 failed case is related to anomaly seg accuracy assertion. 
```
template = ModelTemplate(model_template_id='ote_anomaly_segmentation_stfpm', model_template_path='/usr/src/app/ote_validation/tra...able_code_paths=ExportableCodePaths(default=None, openvino=None), task_type_sort_priority=-1, gigaflops=5.6, size=21.1)
root = '/tmp/ote_cli/'
ote_dir = '/usr/src/app/ote_validation/training_extensions'
args = {'--input': 'data/anomaly/shapes/test/hexagon', '--test-ann-files': 'data/anomaly/segmentation/test.json', '--test-data-roots': 'data/anomaly/shapes', '--train-ann-file': 'data/anomaly/segmentation/train.json', ...}
threshold = 0.01

    def ote_eval_openvino_testing(template, root, ote_dir, args, threshold):
        work_dir, template_work_dir, _ = get_some_vars(template, root)
        command_line = [
            "ote",
            "eval",
            template.model_template_path,
            "--test-ann-file",
            f'{os.path.join(ote_dir, args["--test-ann-files"])}',
            "--test-data-roots",
            f'{os.path.join(ote_dir, args["--test-data-roots"])}',
            "--load-weights",
            f"{template_work_dir}/exported_{template.model_template_id}/openvino.xml",
            "--save-performance",
            f"{template_work_dir}/exported_{template.model_template_id}/performance.json",
        ]
        assert run(command_line, env=collect_env_vars(work_dir)).returncode == 0
        assert os.path.exists(
            f"{template_work_dir}/exported_{template.model_template_id}/performance.json"
        )
        with open(
            f"{template_work_dir}/trained_{template.model_template_id}/performance.json"
        ) as read_file:
            trained_performance = json.load(read_file)
        with open(
            f"{template_work_dir}/exported_{template.model_template_id}/performance.json"
        ) as read_file:
            exported_performance = json.load(read_file)
    
        for k in trained_performance.keys():
>           assert (
                exported_performance[k] > trained_performance[k]
                or abs(trained_performance[k] - exported_performance[k])
                / (trained_performance[k] + 1e-10)
                <= threshold
            ), f"{trained_performance[k]=}, {exported_performance[k]=}"
E           AssertionError: trained_performance[k]=0.29357798165137616, exported_performance[k]=0.28203891801085723

ote_cli/ote_cli/utils/tests.py:215: AssertionError
```

2022-12-12 01:07 UTC, goodsong81 approved these changes

2022-12-12 01:07 UTC, sungmanc approved these changes

2022-12-12 01:09 UTC, merged