[OTX] Update OpenVino version to 2022.3.0
open-edge-platform/training_extensions pull request #1476
Opened 2023-01-02 11:29 UTC by sovrasov

2023-01-03 00:43 UTC, goodsong81 requested changes

2023-01-03 00:43 UTC, goodsong81 commented on requirements/openvino.txt
>  openmodelzoo-modelapi==2022.2.0
Please try the next version that I've just uploaded :)
![image](https://user-images.githubusercontent.com/4629606/210287612-db842dcb-3d57-4f07-9d53-8106e0cdaff6.png)

2023-01-03 07:39 UTC, goodsong81 commented
@sovrasov I heard from Mark that this change should be targeting Geti1.2 so that we need to change the base branch to develop.

2023-01-03 08:46 UTC, sovrasov commented
I have a PR to develop as well https://github.com/openvinotoolkit/training_extensions/pull/1393

2023-02-01 12:36 UTC, goodsong81 commented
@cih9088 Can we close this? When can we expect to replace the NNCF version to PyPI release?
@sovrasov Do you know any info?

2023-02-01 12:42 UTC, cih9088 commented
> @cih9088 Can we close this? When can we expect to replace the NNCF version to PyPI release?

I was told that 2.4.0 would be released in a couple of weeks. Lets go to the official release at once.

2023-02-01 12:43 UTC, samet-akcay commented
> > @cih9088 Can we close this? When can we expect to replace the NNCF version to PyPI release?
> 
> I was told that 2.4.0 would be released in a couple of weeks. Lets update to the official release at once.

@cih9088 , just an update, nncf v2.4.0 has just been released

2023-02-01 12:44 UTC, samet-akcay commented
2 hours ago, actually :)
https://pypi.org/project/nncf/2.4.0/

2023-02-01 12:44 UTC, closed without merging