Update MPA submodule commit ref
open-edge-platform/training_extensions pull request #1478
Opened 2023-01-03 13:47 UTC by vinnamkim

Signed-off-by: Kim, Vinnam <vinnam.kim@intel.com>

2023-01-03 13:48 UTC, vinnamkim commented
run ote-test

2023-01-04 02:09 UTC, sungmanc submitted a review, later dismissed
LGTM.
Test result: http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=pr-ote-test-866&environment=iotg-dev-workstation-08

2023-01-04 15:29 UTC, sovrasov submitted a review, later dismissed

2023-01-09 05:16 UTC, goodsong81 requested changes
Merged MPA PR. Could you update the commit?
https://github.com/openvinotoolkit/model_preparation_algorithm/pull/126

2023-01-09 05:39 UTC, goodsong81 approved these changes

2023-01-09 05:41 UTC, sungmanc approved these changes

2023-01-09 05:45 UTC, merged