disable multi gpu test temporary
open-edge-platform/training_extensions pull request #1527
Opened 2023-01-16 08:27 UTC by eunwoosh

### Summary

- Disable multi GPU test case until resolving a big

### Detail
There is a bug that process is stuck during multi GPU test in CI machine. After resolving the bug, All those tests will be re-enabled again.

2023-01-16 08:29 UTC, harimkang commented on tests/integration/cli/classification/test_classification.py
> +    @pytest.mark.skip  # disable multi GPU test until resolving a bug
How about create Jira-Ticket & Write TODO comments here with Ticket num?

2023-01-16 09:01 UTC, eunwoosh commented on tests/integration/cli/classification/test_classification.py
> +    @pytest.mark.skip  # disable multi GPU test until resolving a bug
Good idea. I updated.

2023-01-17 00:20 UTC, sungmanc submitted a review, later dismissed

2023-01-17 00:23 UTC, goodsong81 requested changes
There is something like skipe(reason="CVS-XXXX")
Please look for other test cases.

2023-01-17 00:37 UTC, goodsong81 approved these changes

2023-01-17 00:41 UTC, yunchu approved these changes

2023-01-17 00:41 UTC, JihwanEom approved these changes

2023-01-17 00:42 UTC, merged