[OTX][Unit-test]Add unit tests for checking otx.algorithms.action.adapters.mmaction.models
open-edge-platform/training_extensions pull request #1605
Opened 2023-02-01 08:20 UTC by jaegukhyun

This PR is for adding unit test codes to check otx.algorithms.action.adapters.mmaction.models

**Modification in otx**
otx/algorithms/action/adapters/mmaction/models/backbones/x3d.py: It is deleted since we don't need adapted X3D for otx after changing mmcv version.
otx/algorithms/action/adapters/mmaction/models/detectors/fast_rcnn.py: 
1. Change order of inputs for ONNXPool3D: It is bug fix, the current one is right
2. Remove inference when the model is not under onnx export: When I firstly designed the forward_infer function, it is for both inference and onnx export. However the current implementation is only for onnx export purpose. Therefore I removed the unnecessary inference part.

**Coverage:**
![image](https://user-images.githubusercontent.com/106788349/215987167-88c3c4b5-339e-47b4-b463-e5f2c5caba1d.png)

2023-02-03 04:51 UTC, harimkang requested changes
![image](https://user-images.githubusercontent.com/38045080/216515191-ae2e8e38-9ea7-48e0-9bd0-ba706cb6f656.png)
This is an error related to this PR. Could you please check it?

2023-02-06 06:57 UTC, jaegukhyun commented
After rebase, the errors disappear
![image](https://user-images.githubusercontent.com/106788349/216903710-ec63cdf6-c798-4b32-aedc-c2a373950811.png)

2023-02-06 08:25 UTC, harimkang approved these changes

2023-02-06 08:38 UTC, supersoob approved these changes

2023-02-06 08:53 UTC, merged