[ANOMALY] Add Anomaly unit tests
open-edge-platform/training_extensions pull request #1665
Opened 2023-02-09 14:46 UTC by ashwinvaidya17

# TODO

- [ ] nncf task
- [ ] openvino task
- [ ] exportable code

2023-02-10 14:06 UTC, ashwinvaidya17 commented
We need to include changes from https://github.com/openvinotoolkit/training_extensions/pull/1662 so that it works in the CI

2023-02-13 14:39 UTC, samet-akcay reviewed
Thank you for your effort. The code looks clean too! This would overall do the job to provide a decent coverage.

I have some comments, but i think we could address these in a follow-up PR for a refactor. 

- It would be great if we utilize pytest fixtures to setup data, model, train and the rest of the workflow. The advantage would be that we would initialize these once and use it throughout the tests. 
- It would be good to have the `assert` statements at the end of each test function. If we have multiple `assert` statements, this might indicate that we could split the test functions.

As I said, I'm providing these comments here for a future reference. Let's address these later.

2023-02-13 14:39 UTC, samet-akcay commented on tests/unit/algorithms/anomaly/helpers/dummy_dataset.py
> +        one_each (bool): Gets one each of each class. Defaults to False.
Can you elaborate this? It took me a while to actually get what exactly it does.

2023-02-13 14:39 UTC, samet-akcay commented on tests/unit/algorithms/anomaly/helpers/dummy_model.py
> +        return batch
```suggestion
    def configure_optimizers(self):
        return None

    def training_step(self, *args, **kwargs):
        pass

    def predict_step(self, batch: Any, batch_idx: int, dataloader_idx: int = 0) -> Any:
        # Just return everything as anomalous
        batch["anomaly_maps"] = batch["pred_masks"] = torch.ones(batch["image"].shape[0], 1, *batch["image"].shape[2:])
        batch["pred_labels"] = batch["pred_scores"] = torch.ones((batch["image"].shape[0]))
        return batch

    def validation_step(self, batch: Any, batch_idx: int, dataloader_idx: int = 0):
        return self.predict_step(batch, batch_idx, dataloader_idx)

    def test_step(self, batch: Any, batch_idx: int, dataloader_idx: int = 0):
        return self.predict_step(batch, batch_idx, dataloader_idx)
```

2023-02-13 14:39 UTC, samet-akcay commented on tests/unit/algorithms/anomaly/tasks/test_inference.py
> +    """Tests the method in the inference task."""
Can you add a description here to explain the steps in details. What would be the scope of this test? This would serve as a future reference

2023-02-13 14:39 UTC, samet-akcay commented on tests/unit/algorithms/anomaly/adapters/callbacks/test_inference_callback.py
> +from tests.unit.algorithms.anomaly.helpers.dummy_dataset import MockDataModule
Just to follow the same naming convention, would it be an idea to name `MockDataModule` to `DummyDataModule`? Is there a specific motivation of naming it as `MockDataModule`?

2023-02-13 14:46 UTC, djdameln requested changes

2023-02-13 14:46 UTC, djdameln commented on tests/unit/algorithms/anomaly/adapters/callbacks/test_inference_callback.py
> +    def test_inference_callback(self, task_type):
Can you add a docstring explaining what exactly is tested here?

2023-02-13 14:46 UTC, djdameln commented on tests/unit/algorithms/anomaly/adapters/callbacks/test_inference_callback.py
> +    def test_inference_callback(self, task_type):
As discussed, we might want to add more tests to cover various use cases and edge cases (possibly in a separate PR). Some suggestion:
- all three task types (cls, det, seg)
- Are heatmaps stored correctly as metadata items?

2023-02-13 14:46 UTC, djdameln commented on tests/unit/algorithms/anomaly/adapters/data/test_dataset.py
> +        assert next(iter(datamodule.predict_dataloader())).keys() == {"image", "label", "index"}
Should we also test the train, val and test dataloaders?

2023-02-13 14:46 UTC, djdameln commented on tests/unit/algorithms/anomaly/config/test_model_config_load.py
> +def test_model_template_loading(model_name, configurable_parameters):
Could you add a docstring here?

2023-02-13 14:46 UTC, djdameln commented on tests/unit/algorithms/anomaly/config/test_model_config_load.py
> +    get_anomalib_config(model_name, configurable_parameters_yaml)
the comment mentions the loaded yaml, but the check targets the created yaml. I guess one of those should be changed.

2023-02-13 14:46 UTC, djdameln commented on tests/unit/algorithms/anomaly/helpers/dummy_dataset.py
> +        return DataLoader(self.dataset, shuffle=False, batch_size=32, num_workers=2, collate_fn=collate_fn)
Not sure if it's a good idea to base our dataset tests on a subclass that overrides some stuff from the parent class. If I'm not wrong, our tests don't actually cover `OTXAnomalyDataModule.predict_dataloader()` now because it is overridden here.

2023-02-13 14:46 UTC, djdameln commented on tests/unit/algorithms/anomaly/tasks/test_inference.py
> +    """Tests the method in the inference task."""
~~method~~ methods

2023-02-13 14:46 UTC, djdameln commented on tests/unit/algorithms/anomaly/tasks/test_inference.py
> +        )
Could you add some comments here explaining the different steps? This test is a bit hard to follow now

2023-02-13 14:46 UTC, djdameln commented on tests/unit/algorithms/anomaly/tasks/test_inference.py
> +    def test_inference(self, task_type, tmpdir):
This test case is quite long and tests a bunch of different things. Do you think it could be split into several smaller tests?

2023-02-13 14:46 UTC, djdameln commented on tests/unit/algorithms/anomaly/tasks/test_train.py
> +        train_task.train(dataset, output_model, TrainParameters())
There seems to be some overlap between this test case and those in `test_nncf.py`, `test_openvino.py`. You could maybe consider using fixtures to abstract away some of the boilerplate code.

2023-02-14 15:46 UTC, djdameln approved these changes
Thanks. I feel the task tests could be simplified and improved a bit further, but I don't want to block you so let's merge this for now.

2023-02-14 15:46 UTC, djdameln commented on tests/unit/algorithms/anomaly/tasks/test_train.py
> +        task_type = setup_task_environment.task_type
Not sure if this is an improvement, but maybe we can revisit this later

2023-02-15 08:21 UTC, ashwinvaidya17 commented on tests/unit/algorithms/anomaly/tasks/test_train.py
> +        task_type = setup_task_environment.task_type
Yeah that was my concern as well. Ideally we should combine all the tasks into a single file and run them in stages to avoid redundant computation.

2023-02-16 08:57 UTC, samet-akcay approved these changes

2023-02-16 08:58 UTC, merged