[DOC] Update README and quick start guide
open-edge-platform/training_extensions pull request #1707
Opened 2023-02-15 15:43 UTC by kprokofi

2023-02-16 01:11 UTC, sungmanc submitted a review, later dismissed
Such a incredible work !

2023-02-16 10:28 UTC, kprokofi commented
I fixed pre-commit tests 
@sungmanc, @harimkang, @goodsong81 , could you please review?

2023-02-16 10:30 UTC, sovrasov commented on QUICK_START_GUIDE.md
> +The current version of OTX was tested under the following environments
Environment? we mention only one

2023-02-16 10:31 UTC, kprokofi commented
Pre-merge is failed, but it doesn't depend on this PR. This is only documentation PR

2023-02-16 10:34 UTC, sungmanc approved these changes, later dismissed
LGTM

2023-02-16 10:48 UTC, goodsong81 requested changes
Great! Thank you for the update.
I'd like to request a tiny change, though.
In addition, I would create a PR soon to align CUDA version to 11.7 actually.

2023-02-16 10:48 UTC, goodsong81 commented on QUICK_START_GUIDE.md
> +tox --devenv venv/otx -e pre-merge
We are specifying tox==4.4.5, and it's `tox devenv` in the (latest) version. :)

2023-02-16 11:14 UTC, kprokofi commented on QUICK_START_GUIDE.md
> +tox --devenv venv/otx -e pre-merge
OK. Thanks!

2023-02-16 11:18 UTC, goodsong81 submitted a review, later dismissed

2023-02-16 11:54 UTC, kprokofi commented
I will reflect changes after Harim fix tomorrow. Please, do not merge now since we found some bug in CLI

2023-02-16 15:01 UTC, GalyaZalesskaya reviewed
Thank you for this update that we really need now

2023-02-16 15:01 UTC, GalyaZalesskaya commented on QUICK_START_GUIDE.md
> +> **_Note:_** each task supports different dataset formats. To know more about which formats are supported by each task, refer to [explanation section](https://openvinotoolkit.github.io/training_exte
To run trainings we need to have datasets in a certain format. For example, for detection task we need the following dataset format:
(ROOT)
```
|---- annotations       
  |---- instances_train.json
  |---- instances_val.json
|---- images       
  |---- train               
    |---- 000.jpg       
  |---- val
```
Can we add here the format example for Detection? Because it's easy to skip this part

2023-02-16 15:01 UTC, GalyaZalesskaya commented on QUICK_START_GUIDE.md
> +
Can you please add here, that in case of omitting `--val-data-roots`, the val folder will be splitted automatically according to annotations_val, and corresponding ``splitted dataset`` folder will be added to workspace, so its paths can be used for training/evaluation?

2023-02-16 15:01 UTC, GalyaZalesskaya commented on QUICK_START_GUIDE.md
> +> **_Note:_** each task supports different dataset formats. To know more about which formats are supported by each task, refer to [explanation section](https://openvinotoolkit.github.io/training_exte
Due to the fact that dataset format is crucial for us, maybe even we can put the note with the appropriate format and annotation naming in the beginning (before describing all commands). I understand that the `tutorials` is a better place for that, but inappropriate format is a source of all issues down the road

2023-02-16 15:01 UTC, GalyaZalesskaya commented on QUICK_START_GUIDE.md
> +It is also possible to start training by just passing the path to dataset roots, then the auto-configuration will be enabled. If you created a workspace with `otx build`, the training process can be
I'd suggest to move this paragraph after code below, because overwise it looks confusing

2023-02-16 15:01 UTC, GalyaZalesskaya commented on QUICK_START_GUIDE.md
> +`otx train` receives `template` as a positional argument. Also, the path to train and val data root should be passed to the CLI to start training. The template name could be taken from the output of
Passing paths is a really tricky part here. Can you please add that --train-data-root can contain the root path to a dataset with  `annotations` and `images`, where images are split into `train` and `val`, so the script finds it automatically?

This is a convenient feature but it's really tricky part, and I even don't know, how to document it properly 🤨

2023-02-16 21:52 UTC, kprokofi commented on QUICK_START_GUIDE.md
> +> **_Note:_** each task supports different dataset formats. To know more about which formats are supported by each task, refer to [explanation section](https://openvinotoolkit.github.io/training_exte
We make quick start general overview. I leave a link to explanation section where all supported dataset formats can be found for each task. However, in build and train sections I will cover some corner cases

2023-02-16 23:08 UTC, kprokofi commented
@GalyaZalesskaya I reflected your comments:
1) I move "note" for the dataset formats to the beginning.
2) I cover corner cases with otx build and train with train and val roots
3) I added example with COCO dataset when we have val and train in one root folder on how to pass roots in that case

@goodsong81 @harimkang @sungmanc I aligned changes from Harim fix (thanks for that!) - now I think PR is ready to merge

2023-02-17 00:14 UTC, harimkang approved these changes
Thank you for your efforts. That's a good Doc!

2023-02-17 04:14 UTC, goodsong81 approved these changes
Great!

2023-02-17 04:14 UTC, merged

2023-02-17 04:36 UTC, goodsong81 commented on QUICK_START_GUIDE.md
> +tox devenv venv/otx -e pre-merge
Nit: `python -m pip install -r requirements/dev.txt` is actually omitted here, but users could just hit `pip install otx`.