[TEST] Add unit tests for MPA classification-related losses and heads
open-edge-platform/training_extensions pull request #1709
Opened 2023-02-15 21:55 UTC by sovrasov

2023-02-16 08:04 UTC, sovrasov commented
```
FAILED tests/unit/cli/utils/test_parser.py::test_get_parser_and_hprams_data_with_template
FAILED tests/unit/cli/utils/test_parser.py::test_get_parser_and_hprams_data
= 2 failed, 1734 passed, 8 skipped, 2 xpassed, 549 warnings in 266.25s (0:04:26) =
```
@harimkang @sungmanc could you have a look at the failure of the parsers-related tests?

2023-02-16 08:08 UTC, harimkang commented
> ```
> FAILED tests/unit/cli/utils/test_parser.py::test_get_parser_and_hprams_data_with_template
> FAILED tests/unit/cli/utils/test_parser.py::test_get_parser_and_hprams_data
> = 2 failed, 1734 passed, 8 skipped, 2 xpassed, 549 warnings in 266.25s (0:04:26) =
> ```
> 
> @harimkang @sungmanc could you have a look at the failure of the parsers-related tests?

I made a hot-fix PR https://github.com/openvinotoolkit/training_extensions/pull/1712 for this. This is the current integration test running. It will be merged soon.

2023-02-17 00:25 UTC, harimkang requested changes
The name of the file containing the test code must be in the format test_*.py.
CI is currently not collecting these test cases.

2023-02-17 10:56 UTC, harimkang approved these changes

2023-02-17 11:12 UTC, kprokofi approved these changes

2023-02-17 11:12 UTC, merged