[DOC] Add document for action detection explanation
open-edge-platform/training_extensions pull request #1767
Opened 2023-02-21 04:39 UTC by jaegukhyun

This PR includes adding documentation for explanation of action detection algorithms
N/A part should be added soon

2023-02-21 12:03 UTC, sungmanc commented
I think this PR is still WIP. So I added [WIP] tag in front of the title. If I'm wrong, please re-correct the title.

2023-02-21 13:35 UTC, kprokofi requested changes

2023-02-21 13:35 UTC, kprokofi commented on docs/source/guide/explanation/algorithms/action/action_detection.rst
> +    $ otx train --template otx/algorithms/action/configs/detection/x3d_fast_rcnn/template.yaml --train-data-root <path_to_data_root/train> --val-data-root <path_to_data_root/val>
```suggestion
    $ otx train otx/algorithms/action/configs/detection/x3d_fast_rcnn/template.yaml --train-data-root <path_to_data_root/train> --val-data-root <path_to_data_root/val>

```

2023-02-21 17:21 UTC, kprokofi approved these changes

2023-02-22 00:09 UTC, sungmanc approved these changes

2023-02-22 00:09 UTC, merged