Removed nncf_quantization_pruning part from efficientnet_v2 compression config
open-edge-platform/training_extensions pull request #1945
Opened 2023-03-27 14:36 UTC by nikita-savelyevv

### Summary
Pruning is not supported for EfficientNet-v2 but NNCF, but config still contains `nncf_quantization_pruning` part. Removed `nncf_quantization_pruning` from compression config.

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md)
- [ ] I have updated the [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

### License

- [x] I submit _my code changes_ under the same [MIT License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

2023-03-28 00:45 UTC, sungmanc requested changes
Thanks for contribution ! BTW, could you add proper milestone and fill the checklist from PR template?

2023-03-28 11:02 UTC, nikita-savelyevv commented
Decided to solve the discrepancy the other way around and remove `nncf_quantization_pruning` from compression config altogether, since pruning is not supported for this model.

2023-03-30 04:51 UTC, harimkang approved these changes

2023-03-30 04:55 UTC, goodsong81 approved these changes

2023-03-30 04:56 UTC, merged