🔨 Replace shapes with hazelnut dataset
open-edge-platform/training_extensions pull request #1948
Opened 2023-03-28 08:03 UTC by ashwinvaidya17

### Summary

The metrics computed on the shapes dataset led to poor regression results. This PR replaces that dataset with a more realistic hazelnut dataset. This leads to higher multi-score performance.

### How to test

- Just run `pytest tests/e2e/cli/anomaly/` and `pytest tests/unit/algorithms/anomaly`

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md)
- [ ] I have updated the [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) accordingly
- [x] I have added tests to cover my changes
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

### License

- [x] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
```

2023-03-28 10:01 UTC, sungmanc requested changes
LGTM for changing dataset, however, could you add milestone to 1.2.0 and edit the tile ?
We don't use [FIX] [ENHANCE] prefix anymore :)

2023-03-28 23:08 UTC, sungmanc approved these changes

2023-03-28 23:10 UTC, sungmanc approved these changes
LGTM.

FYI, you can add the milestone in this sidebar
![image](https://user-images.githubusercontent.com/80735344/228387009-64c17dd9-9baa-4842-824a-3115a4c2a045.png)

2023-03-29 00:22 UTC, sinunu approved these changes

2023-03-29 00:27 UTC, eunwoosh approved these changes

2023-03-29 00:55 UTC, merged