Add legacy ssd-like IRs support
open-edge-platform/training_extensions pull request #1970
Opened 2023-04-04 14:15 UTC by sovrasov

### Summary

In old SSD-like IRs bbox and label layers have different shapes than in current implementation. Wrapper was fixes to support both IR formats.

### How to test

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [x] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

2023-04-04 14:25 UTC, goodsong81 requested changes
Thank you so much for the fix. We need to be careful for this kind of change in the future. By the way, could you update the change log? It's a new convention and I think this change is worth to note. :)

2023-04-05 01:27 UTC, goodsong81 approved these changes
LGTM!

2023-04-05 01:51 UTC, jaegukhyun approved these changes
Is this for old version of openvino model inference? It would be nice if you add some summary and motivation of this work.

2023-04-05 08:00 UTC, cih9088 commented on otx/algorithms/detection/adapters/openvino/model_wrappers/openvino_models.py
> +        if bboxes.shape[0] == 1:
Why do we need this condition? `squeeze` removes the first dim if the first dim is 1, does nothing otherwise.

2023-04-05 08:00 UTC, cih9088 commented on otx/algorithms/detection/adapters/openvino/model_wrappers/openvino_models.py
> +        if labels.shape[0] == 1:
Why do we need this condition? `squeeze` removes the first dim if the first dim is 1, does nothing otherwise.

2023-04-05 09:15 UTC, sovrasov commented on otx/algorithms/detection/adapters/openvino/model_wrappers/openvino_models.py
> +        if bboxes.shape[0] == 1:
We can squeeze the first dimension only if it equals to 1. For old IRs from previous OTE versions that's not true and squeeze raises an exception.

2023-04-05 09:15 UTC, sovrasov commented on otx/algorithms/detection/adapters/openvino/model_wrappers/openvino_models.py
> +        if labels.shape[0] == 1:
We can squeeze the first dimension only if it equals to 1. For old IRs from previous OTE versions that's not true and squeeze raises an exception.

2023-04-05 09:28 UTC, sovrasov commented
> Is this for old version of openvino model inference? It would be nice if you add some summary and motivation of this work.

Added a brief description in summary

2023-04-06 00:26 UTC, cih9088 commented on otx/algorithms/detection/adapters/openvino/model_wrappers/openvino_models.py
> +        if bboxes.shape[0] == 1:
Ahh. The object is numpy array not pytorch tesnor.

2023-04-06 00:27 UTC, cih9088 commented on otx/algorithms/detection/adapters/openvino/model_wrappers/openvino_models.py
> +        if labels.shape[0] == 1:
Ahh. The object is numpy array not pytorch tesnor.

2023-04-06 00:27 UTC, cih9088 approved these changes

2023-04-06 09:04 UTC, merged