[WIP]Refactor action tasks and remove unused modules
open-edge-platform/training_extensions pull request #1993
Opened 2023-04-10 06:39 UTC by jaegukhyun

### Summary

1. Change action task structure to match with other tasks
2. Divide learning setting(recipe) and model setting(model.py) video recognition configs
3. Add progress bar for inference task for both pytorch task and openvino task(action) 
4. Remove unused common modules
5. Remove unit test for unused common modules
6. Change unit test for removing unused common modules
7. Add new unit test for new action task

### How to test
unit, cli, e2e test

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

2023-04-11 06:40 UTC, sungmanc requested changes
Could you also update the CHANGELOG?
https://github.com/jaegukhyun/training_extensions/blob/action-task-refactoring/CHANGELOG.md

2023-04-11 06:59 UTC, jaegukhyun commented
> Could you also update the CHANGELOG? https://github.com/jaegukhyun/training_extensions/blob/action-task-refactoring/CHANGELOG.md

Done.

2023-04-11 07:00 UTC, sungmanc commented
How about adding detection refactoring to CHANGELOG in this PR? we might miss that in previous PR

2023-04-11 07:02 UTC, jaegukhyun commented
> How about adding detection refactoring to CHANGELOG in this PR? we might miss that in previous PR

It will be added in this PR
https://github.com/openvinotoolkit/training_extensions/pull/1997

2023-04-11 07:04 UTC, sungmanc submitted a review, later dismissed

2023-04-12 03:07 UTC, eunwoosh reviewed
Nice work! I left some comments

2023-04-12 03:07 UTC, eunwoosh commented on tests/unit/algorithms/action/adapters/mmaction/test_task.py
> +    def test_evaluate(self) -> None:
Could you divide this as three test cases?

2023-04-12 03:07 UTC, eunwoosh commented on otx/algorithms/action/adapters/mmaction/data/cls_dataset.py
> +        self.CLASSES = list(label.name for label in labels)
```suggestion
        self.CLASSES = [label.name for label in labels]
```
It doen't matter, but this is more recommended way :)

2023-04-12 03:07 UTC, eunwoosh commented on otx/algorithms/action/adapters/mmaction/data/det_dataset.py
> +        self.CLASSES = list(label.name for label in labels)
```suggestion
        self.CLASSES = [label.name for label in labels]
```
same as above

2023-04-12 03:07 UTC, eunwoosh commented on otx/algorithms/action/task.py
> +            # output_model.model_status = ModelStatus.FAILED
Can this line be removed? then how about removing it?

2023-04-12 03:07 UTC, eunwoosh commented on otx/algorithms/action/task.py
> +        logger.info(f"Final model performance: {str(performance)}")
```suggestion
        logger.info(f"Final model performance: {performance}")
```
maybe It could be

2023-04-12 03:07 UTC, eunwoosh commented on otx/algorithms/action/adapters/mmaction/task.py
> +        if bool(fp16):
```suggestion
        if fp16:
```

2023-04-12 03:07 UTC, eunwoosh commented on otx/algorithms/action/adapters/mmaction/task.py
> +                mmdet_version=__version__ + get_git_hash()[:7],
```suggestion
                mmaction2_version=__version__ + get_git_hash()[:7],
```
isn't it right?

2023-04-12 03:07 UTC, eunwoosh commented on otx/algorithms/action/adapters/mmaction/task.py
> +        if len(best_ckpt_path) > 0:
```suggestion
        if best_ckpt_path:
```
it doesn't matter, it's recommended way to check empty list

2023-04-12 03:07 UTC, eunwoosh commented on otx/algorithms/action/adapters/mmaction/task.py
> +
```suggestion
prog_bar.file.write("\n")
```
I don't konw certainly, but I saw this code exists after progress bar update. (e.g. otx/algorithms/common/adapters/mmcv/hooks/eval_hook.py)
how about to add it?

2023-04-12 06:52 UTC, jaegukhyun commented
> Nice work! I left some comments

Thank you for your detailed review, I reflected it. Could you check them and resolve conversation?

2023-04-12 06:58 UTC, eunwoosh approved these changes

2023-04-12 07:48 UTC, sungmanc approved these changes

2023-04-12 07:50 UTC, eunwoosh approved these changes

2023-04-12 08:03 UTC, merged