Fixes in exportable code
open-edge-platform/training_extensions pull request #2031
Opened 2023-04-18 21:23 UTC by GalyaZalesskaya

### Summary

#### Fixes in exportable code:

- Fixed torch imports in `otx/algorithms/common/utils/utils.py`, so the demo in exportable code doesn't require torch to run anymore
- Removed the condition that ACTION_CLASSIFICATION and ACTION_DETECTION TaskType and Domain appear in enum only if `FEATURE_FLAGS_OTX_ACTION_TASKS` flag is used. This caused an issue that [enum initialization](https://github.com/openvinotoolkit/training_extensions/blob/6cbac4689979fc44df20532c7207497af38bf072/otx/api/entities/model_template.py#L117) happened before initializing FEATURE_FLAGS_OTX_ACTION_TASKS as 1 for CLI tasks [here](https://github.com/openvinotoolkit/training_extensions/blob/63a1a0408c1e0310d3eb31b21aaebb13ff4ae0b7/otx/cli/__init__.py#L11), so the demo failed with attribute error for ACTION CLASSIFICATION.

#### Enhances:
- Removed coping `__pycache__` to deployed zip from exportable code  
- Moved utility function for saving the demo output to `otx.api.utils` to avoid cross-dependencies on otx.cli in exportable code package

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [x] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

2023-04-18 23:53 UTC, sungmanc reviewed
Left some comments.

2023-04-18 23:53 UTC, sungmanc commented on otx/api/entities/label.py
> +    ACTION_CLASSIFICATION = auto()
As far as I know, this flag is important for Geti. could you check? @goodsong81

2023-04-18 23:53 UTC, sungmanc commented on otx/api/entities/model_template.py
> +    ACTION_CLASSIFICATION = 14, TaskInfo(
Same with above

2023-04-19 03:59 UTC, goodsong81 requested changes
ACTION_CLASSIFICATION/DETECTION should not be exposed to Geti yet, it's the reason why we adopted the `FEATURE_FLAG` mechanism. Can you fix the issue in other ways?

2023-04-19 09:06 UTC, sovrasov commented on otx/algorithms/action/adapters/openvino/task.py
> +                # skip coping __pycache__ folder
It looks like this comment is useless

2023-04-19 09:18 UTC, GalyaZalesskaya commented on otx/algorithms/action/adapters/openvino/task.py
> +                # skip coping __pycache__ folder
Removed them, thank you

2023-04-19 09:19 UTC, GalyaZalesskaya commented
@sungmanc @goodsong81 Thank you for the clarification about ACTION_CLASSIFICATION/DETECTION flag, I fixed its usage

2023-04-20 01:52 UTC, goodsong81 approved these changes

2023-04-20 01:54 UTC, merged