Action task supports multi GPU training
open-edge-platform/training_extensions pull request #2057
Opened 2023-04-24 06:02 UTC by eunwoosh

### Summary
This PR enables multi GPU training to action task.
Current multi GPU training needs to be refactored because code flow for multi GPU enablement in each tasks are all different.
I'll refactored it after this pr is merged and at that time I'll implement unit test for that.

### How to test

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [x] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [x] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

2023-04-24 06:27 UTC, jaegukhyun requested changes
LGTM!. Could you add multi gpu test for action detection?

2023-04-24 06:32 UTC, eunwoosh commented
> LGTM!. Could you add multi gpu test for action detection?

Thanks! it's not hard but my intention is adding as little as possible test to integration test to reduce test time.
Is it necessary to add test in detection task also? If yes, then I'll add it too.

2023-04-24 06:34 UTC, jaegukhyun commented
> > LGTM!. Could you add multi gpu test for action detection?
> 
> Thanks! it's not hard but my intention is adding as little as possible test to integration test to reduce test time. Is it necessary to add test in detection task also? If yes, then I'll add it too.

It make sense to me. Could you add multi-gpu test for action classification and action detection in e2e tests?
I think at least e2e should check all TC

2023-04-24 06:48 UTC, eunwoosh commented
> It make sense to me. Could you add multi-gpu test for action classification and action detection in e2e tests? I think at least e2e should check all TC

I added it.

2023-04-24 06:49 UTC, jaegukhyun approved these changes, later dismissed

2023-04-24 07:18 UTC, sungmanc commented on otx/algorithms/action/adapters/mmaction/task.py
> +    def _configure_device(self, cfg, training):
Could you add the proper type-hint for this method?

2023-04-24 07:43 UTC, eunwoosh commented on otx/algorithms/action/adapters/mmaction/task.py
> +    def _configure_device(self, cfg, training):
I updated it :)

2023-04-24 09:43 UTC, goodsong81 requested changes
LGTM, but could you please fix one thing below?

2023-04-24 09:43 UTC, goodsong81 commented on CHANGELOG.md
> +- Action task supports multi GPU training.
Please add PR link :)

2023-04-24 10:06 UTC, eunwoosh commented on CHANGELOG.md
> +- Action task supports multi GPU training.
Thanks for pointing it. I added it.

2023-04-24 14:14 UTC, jaegukhyun approved these changes

2023-04-24 14:21 UTC, sungmanc approved these changes

2023-04-25 04:44 UTC, eunwoosh commented on CHANGELOG.md
> +- Action task supports multi GPU training.
Could you approve my PR if it's ok?

2023-04-25 04:46 UTC, goodsong81 approved these changes

2023-04-25 04:46 UTC, merged