Fix Tiling NNCF
open-edge-platform/training_extensions pull request #2081
Opened 2023-04-26 16:32 UTC by eugene123tw

### Summary
Fix Tiling NNCF test pipeline

### How to test

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

2023-04-27 01:58 UTC, cih9088 commented on otx/algorithms/detection/adapters/mmdet/nncf/builder.py
> +
```suggestion
    # replace image loading pipeline with `LoadImage()`
    test_pipeline = [LoadImage()] + [
        pipeline for pipeline in config.data.test.pipeline if not pipeline.type.startswith("LoadImage")
    ]
```

2023-04-27 02:30 UTC, jaegukhyun requested changes
Overall implementation looks good to me. Could you check integration test failure, In addition it would be nice if you add e2e tiling det, iseg test results

2023-04-27 09:28 UTC, eugene123tw commented on otx/algorithms/detection/adapters/mmdet/nncf/builder.py
> +
Done

2023-04-27 11:12 UTC, jaegukhyun reviewed
Could you explain why we need separate dataset for tiling instance segmentation?

2023-04-27 14:19 UTC, eugene123tw commented
> Could you explain why we need separate dataset for tiling instance segmentation?

The change is to ensure a more effective evaluation of our tiling capabilities. While the current dataset may be appropriate for normal object detection, it contains large objects that do not effectively test the limits of our tiling algorithms. Therefore, I think it'd be better to use a more suitable dataset to assess our tiling capabilities accurately.

2023-04-27 23:18 UTC, cih9088 submitted a review, later dismissed

2023-04-28 14:28 UTC, eugene123tw commented
@jaegukhyun There are 3 failed cases related to nncf validate fq

```
==================================================================================================================================== FAILURES ====================================================================================================================================
_______________________________________________________________________________________________ TestToolsTilingDetection.test_nncf_validate_fq[Custom_Object_Detection_Gen3_ATSS] ________________________________________________________________________________________________

self = <tests.e2e.cli.detection.test_tiling_detection.TestToolsTilingDetection object at 0x7f2884c33e80>
template = ModelTemplate(model_template_id='Custom_Object_Detection_Gen3_ATSS', model_template_path='/home/yuchunli/training_exte...paths=ExportableCodePaths(default=None, openvino=None), task_type_sort_priority=-1, gigaflops=20.6, size=9.1, hpo=None)
tmp_dir_path = PosixPath('/tmp/tmp278z3arm/tiling_det')

    @e2e_pytest_component
    @pytest.mark.skipif(TT_STABILITY_TESTS, reason="This is TT_STABILITY_TESTS")
    @pytest.mark.parametrize("template", templates, ids=templates_ids)
    def test_nncf_validate_fq(self, template, tmp_dir_path):
        tmp_dir_path = tmp_dir_path / "tiling_det"
        if template.entrypoints.nncf is None:
            pytest.skip("nncf entrypoint is none")
    
>       nncf_validate_fq_testing(template, tmp_dir_path, otx_dir, "detection", type(self).__name__)

tests/e2e/cli/detection/test_tiling_detection.py:219: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_suite/run_test_command.py:559: in nncf_validate_fq_testing
    _validate_fq_in_xml(xml_path, path_to_ref_data, "nncf", test_name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

xml_path = '/tmp/tmp278z3arm/tiling_det/otx/algorithms/detection/configs/detection/mobilenetv2_atss/exported_nncf_Custom_Object_Detection_Gen3_ATSS/openvino.xml'
path_to_ref_data = '/home/yuchunli/training_extensions/tests/e2e/cli/detection/reference/Custom_Object_Detection_Gen3_ATSS/compressed_model.yml', compression_type = 'nncf', test_name = 'TestToolsTilingDetection'

    def _validate_fq_in_xml(xml_path, path_to_ref_data, compression_type, test_name):
        num_fq = get_number_of_fakequantizers_in_xml(xml_path)
        assert os.path.exists(path_to_ref_data), f"Reference file does not exist: {path_to_ref_data} [num_fq = {num_fq}]"
    
        with open(path_to_ref_data, encoding="utf-8") as stream:
            ref_data = yaml.safe_load(stream)
        ref_num_fq = ref_data.get(test_name, {}).get(compression_type, {}).get("number_of_fakequantizers", -1)
>       assert num_fq == ref_num_fq, f"Incorrect number of FQs in optimized model: {num_fq} != {ref_num_fq}"
E       AssertionError: Incorrect number of FQs in optimized model: 155 != -1

tests/test_suite/run_test_command.py:475: AssertionError
________________________________________________________________________________________________ TestToolsTilingDetection.test_nncf_validate_fq[Custom_Object_Detection_Gen3_SSD] ________________________________________________________________________________________________

self = <tests.e2e.cli.detection.test_tiling_detection.TestToolsTilingDetection object at 0x7f2884c321d0>
template = ModelTemplate(model_template_id='Custom_Object_Detection_Gen3_SSD', model_template_path='/home/yuchunli/training_exten..._paths=ExportableCodePaths(default=None, openvino=None), task_type_sort_priority=-1, gigaflops=9.4, size=7.6, hpo=None)
tmp_dir_path = PosixPath('/tmp/tmp278z3arm/tiling_det')

    @e2e_pytest_component
    @pytest.mark.skipif(TT_STABILITY_TESTS, reason="This is TT_STABILITY_TESTS")
    @pytest.mark.parametrize("template", templates, ids=templates_ids)
    def test_nncf_validate_fq(self, template, tmp_dir_path):
        tmp_dir_path = tmp_dir_path / "tiling_det"
        if template.entrypoints.nncf is None:
            pytest.skip("nncf entrypoint is none")
    
>       nncf_validate_fq_testing(template, tmp_dir_path, otx_dir, "detection", type(self).__name__)

tests/e2e/cli/detection/test_tiling_detection.py:219: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_suite/run_test_command.py:559: in nncf_validate_fq_testing
    _validate_fq_in_xml(xml_path, path_to_ref_data, "nncf", test_name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

xml_path = '/tmp/tmp278z3arm/tiling_det/otx/algorithms/detection/configs/detection/mobilenetv2_ssd/exported_nncf_Custom_Object_Detection_Gen3_SSD/openvino.xml'
path_to_ref_data = '/home/yuchunli/training_extensions/tests/e2e/cli/detection/reference/Custom_Object_Detection_Gen3_SSD/compressed_model.yml', compression_type = 'nncf', test_name = 'TestToolsTilingDetection'

    def _validate_fq_in_xml(xml_path, path_to_ref_data, compression_type, test_name):
        num_fq = get_number_of_fakequantizers_in_xml(xml_path)
        assert os.path.exists(path_to_ref_data), f"Reference file does not exist: {path_to_ref_data} [num_fq = {num_fq}]"
    
        with open(path_to_ref_data, encoding="utf-8") as stream:
            ref_data = yaml.safe_load(stream)
        ref_num_fq = ref_data.get(test_name, {}).get(compression_type, {}).get("number_of_fakequantizers", -1)
>       assert num_fq == ref_num_fq, f"Incorrect number of FQs in optimized model: {num_fq} != {ref_num_fq}"
E       AssertionError: Incorrect number of FQs in optimized model: 67 != -1

tests/test_suite/run_test_command.py:475: AssertionError
_________________________________________________________________________________________________ TestToolsTilingDetection.test_nncf_validate_fq[Custom_Object_Detection_YOLOX] __________________________________________________________________________________________________

self = <tests.e2e.cli.detection.test_tiling_detection.TestToolsTilingDetection object at 0x7f2884c30f40>
template = ModelTemplate(model_template_id='Custom_Object_Detection_YOLOX', model_template_path='/home/yuchunli/training_extensio...paths=ExportableCodePaths(default=None, openvino=None), task_type_sort_priority=-1, gigaflops=6.5, size=20.4, hpo=None)
tmp_dir_path = PosixPath('/tmp/tmp278z3arm/tiling_det')

    @e2e_pytest_component
    @pytest.mark.skipif(TT_STABILITY_TESTS, reason="This is TT_STABILITY_TESTS")
    @pytest.mark.parametrize("template", templates, ids=templates_ids)
    def test_nncf_validate_fq(self, template, tmp_dir_path):
        tmp_dir_path = tmp_dir_path / "tiling_det"
        if template.entrypoints.nncf is None:
            pytest.skip("nncf entrypoint is none")
    
>       nncf_validate_fq_testing(template, tmp_dir_path, otx_dir, "detection", type(self).__name__)

tests/e2e/cli/detection/test_tiling_detection.py:219: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_suite/run_test_command.py:559: in nncf_ [...]

2023-05-02 00:07 UTC, cih9088 approved these changes, later dismissed

2023-05-02 01:06 UTC, jaegukhyun requested changes
Could you check e2e tiling instance segmentation e2e test too? And please change nncf fq number in reference.

2023-05-02 01:08 UTC, sungmanc requested changes
We could remove useless annotation files.
(image_info***.json, stuff_***.json)

2023-05-02 10:49 UTC, jaegukhyun submitted a review, later dismissed

2023-05-02 11:12 UTC, jaegukhyun approved these changes

2023-05-02 13:01 UTC, goodsong81 approved these changes

2023-05-02 15:17 UTC, eugene123tw commented
@jaegukhyun e2e result from test_tiling_instseg
```
tests/e2e/cli/instance_segmentation/test_tiling_instseg.py::TestToolsTilingInstanceSegmentation::test_pot_eval[Custom_Counting_Instance_Segmentation_MaskRCNN_ResNet50] [*] Update data configuration file to: /tmp/tmpjixxlccv/tiling_ins_seg/otx/algorithms/detection/configs/instance_segmentation/resnet50_maskrcnn/data.yaml
2023-05-03 00:12:05,661 | INFO : Loading OpenVINO OTXDetectionTask
2023-05-03 00:12:06,498 | INFO : OpenVINO task initialization completed
2023-05-03 00:12:06,499 | INFO : Start OpenVINO inference
2023-05-03 00:12:07,242 | INFO : 0.7425226770001245 secs
2023-05-03 00:12:07,911 | INFO : 0.6690832060003231 secs
2023-05-03 00:12:07,911 | INFO : Avg time per image: 0.7058029415002238 secs
2023-05-03 00:12:07,911 | INFO : Total time: 1.4116058830004476 secs
2023-05-03 00:12:07,911 | INFO : OpenVINO inference completed
2023-05-03 00:12:07,911 | INFO : Start OpenVINO metric evaluation
2023-05-03 00:12:07,918 | INFO : OpenVINO metric evaluation completed
Performance(score: 0.0, dashboard: (1 metric groups))
/home/yuchunli/training_extensions/venv/otx/lib/python3.10/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/home/yuchunli/training_extensions/venv/otx/lib/python3.10/site-packages/openvino/offline_transformations/__init__.py:10: FutureWarning: The module is private and following namespace `offline_transformations` will be removed in the future, use `openvino.runtime.passes` instead!
  warnings.warn(
PASSED

=============================== warnings summary ===============================
venv/otx/lib/python3.10/site-packages/_pytest/config/__init__.py:747
  /home/yuchunli/training_extensions/venv/otx/lib/python3.10/site-packages/_pytest/config/__init__.py:747: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: tests.test_suite.fixtures
    self.import_plugin(import_spec)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============ 34 passed, 14 skipped, 1 warning in 4400.66s (1:13:20) ===========
```

2023-05-03 00:37 UTC, merged