[Fix] Assign label information to heatmap in resultmedia
open-edge-platform/training_extensions pull request #2220
Opened 2023-06-06 15:38 UTC by djdameln

### Summary

Previously the predicted label was not passed to the heatmap in the result media. Fixed by specifying a value for the `label` argument when creating the `ResultMediaEntity` object.

### How to test

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [x] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

2023-06-06 15:41 UTC, samet-akcay approved these changes

2023-06-06 16:03 UTC, sovrasov approved these changes

2023-06-06 23:18 UTC, sungmanc approved these changes
Will we release this as 1.2.3.4?

2023-06-07 01:10 UTC, goodsong81 commented
@djdameln @samet-akcay Is this an urgent fix? Why don't you just fix in the develop branch?

2023-06-07 03:53 UTC, goodsong81 requested changes
Please retarget this PR to develop branch.

2023-06-07 11:19 UTC, djdameln commented
> Is this an urgent fix? Why don't you just fix in the develop branch?

It's a fix for this ticket: https://jira.devtools.intel.com/browse/CVS-112273, which affects 1.5 and 1.6 and is labeled as high priority.

2023-06-08 00:46 UTC, goodsong81 approved these changes

2023-06-08 00:47 UTC, merged