bugfix: enabling lr scale during distributed training
open-edge-platform/training_extensions pull request #2254
Opened 2023-06-20 06:57 UTC by eunwoosh

### Summary

- Current OTX doesn't scale learning rate when multi GPU training. Fix it to scale lr.

### How to test

### Checklist

- [x] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

2023-06-20 07:59 UTC, sungmanc reviewed
LGTM, w/ minor comments for the CHANGELOG.

2023-06-20 07:59 UTC, sungmanc commented on CHANGELOG.md
> +- Fix the bug that learning rate ins't scaled when multi-GPU trianing (<https://github.com/openvinotoolkit/training_extensions/pull/2254>)
```suggestion
- Fix the bug that learning rate isn't scaled when multi-GPU trianing is enabled(<https://github.com/openvinotoolkit/training_extensions/pull/2254>)
```

2023-06-20 08:20 UTC, sungmanc approved these changes, later dismissed

2023-06-21 07:22 UTC, jaegukhyun requested changes
Could you add unit test for action task?

2023-06-21 07:35 UTC, eunwoosh commented
> Could you add unit test for action task?

Sure, I implemented it.

2023-06-21 09:01 UTC, jaegukhyun approved these changes

2023-06-21 09:01 UTC, sungmanc approved these changes

2023-06-21 10:02 UTC, merged