Move SegNext models from experimental to custom models
open-edge-platform/training_extensions pull request #2312
Opened 2023-07-06 11:25 UTC by kprokofi

### Summary

### How to test

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

2023-07-06 11:37 UTC, kprokofi commented
![image](https://github.com/openvinotoolkit/training_extensions/assets/68103869/57c66fc4-12b2-4516-a4b7-48c158ad794f)
e2e passed for SegNext-t

2023-07-06 12:13 UTC, goodsong81 requested changes
Thank you for the great work, @kprokofi.
BTW, Mark decided not to update the default det/seg models in Geti1.8 timeline for safety. The classification model, DEIT, only will be added as custom model. So, let's target this PR (and requirement) to OTX1.5. We can merge this PR to develop after creating releases/1.4.0.
c.c. @sovrasov

2023-08-02 17:05 UTC, sovrasov commented
@kprokofi please update the PR. Now we have `model_category` in template to map models to Geti tasks, so experimental_ prefix doesn't make sense anymore.

2023-08-09 11:43 UTC, sovrasov commented on tests/e2e/cli/semantic_segmentation/test_segmentation.py
> +        if not os.path.exists(os.path.join(template.model_template_path[:-14], "selfsl")):
We agreed to use Pathlib in OTX. Also, `path.parent` may solve the slitting issue without indexing lists

2023-08-09 12:41 UTC, sovrasov commented on tests/e2e/cli/semantic_segmentation/test_segmentation.py
> +        # if Path(template.model_template_path, )
Please del commented code

2023-08-10 00:04 UTC, sungmanc approved these changes
LGTM for me, have two simple questions.

1. Is there any reason to change the `os` --> `path` to represent the file path and directory?
2. Is `early_stop_patience` value set by experiments? It seems that it's quite large if we use the large dataset

2023-08-10 08:21 UTC, kprokofi commented
> LGTM for me, have two simple questions.
> 
> 1. Is there any reason to change the `os` --> `path` to represent the file path and directory?
> 2. Is `early_stop_patience` value set by experiments? It seems that it's quite large if we use the large dataset

1. We agreed to use Pathlib instead of os.path, so I started with segmentation and changed os to path. Thre is no other reasons.
2.  After experiments on small datasets (10-40 images) it turned out that SegNext tends to show around 0 metric during first epochs and training stops because of early stopping. However, if we train model with more epochs - the results got much better (as expected). So, I increased early stopping lower boundary. 
Since our main target is Geti, it seems reasonable. On large datasets first 15 epochs without early stopping looks not too much, I think. If it cause some concerns and training time relate issues, I can think about some heuristic based on dataset length in the future

2023-08-10 08:37 UTC, sovrasov approved these changes

2023-08-10 09:24 UTC, sungmanc commented
> > LGTM for me, have two simple questions.
> > 
> > 1. Is there any reason to change the `os` --> `path` to represent the file path and directory?
> > 2. Is `early_stop_patience` value set by experiments? It seems that it's quite large if we use the large dataset
> 
> 1. We agreed to use Pathlib instead of os.path, so I started with segmentation and changed os to path. Thre is no other reasons.
> 2. After experiments on small datasets (10-40 images) it turned out that SegNext tends to show around 0 metric during first epochs and training stops because of early stopping. However, if we train model with more epochs - the results got much better (as expected). So, I increased early stopping lower boundary.
>    Since our main target is Geti, it seems reasonable. On large datasets first 15 epochs without early stopping looks not too much, I think. If it cause some concerns and training time relate issues, I can think about some heuristic based on dataset length in the future

Thanks for your replying ! BTW, what I concerned about is `early_stop_patience`, not `early_stop_start`. However, it's not important for now.

2023-08-11 08:04 UTC, kprokofi commented
@goodsong81 Could you approve, please?

2023-08-11 08:45 UTC, goodsong81 approved these changes
Oh, sorry for late review. I thought I've done already.
LGTM! :)

2023-08-11 08:45 UTC, merged