Update for release 1.4
open-edge-platform/training_extensions pull request #2380
Opened 2023-07-19 23:55 UTC by yunchu

### Summary

### How to test

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

2023-07-20 01:51 UTC, goodsong81 requested changes
To prevent merge by mistake

2023-07-20 08:44 UTC, sungmanc submitted a review, later dismissed

2023-07-20 08:44 UTC, goodsong81 requested changes

2023-07-20 08:44 UTC, goodsong81 commented on docs/source/guide/release_notes/index.rst
> +[v1.40] (3Q23)
```suggestion
[v1.4.0] (3Q23)
```

2023-07-20 23:58 UTC, jaegukhyun approved these changes

2023-07-21 00:04 UTC, chuneuny-emily approved these changes

2023-07-21 00:15 UTC, merged