RTM-Det Inst
open-edge-platform/training_extensions pull request #2497
Opened 2023-09-12 10:15 UTC by eugene123tw

### Summary

### How to test

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

2023-10-19 06:31 UTC, goodsong81 requested changes
Thank you for the great work!
I'd like to request a small change, and a little bit more tests.
Unit tests for modules copied from mmlab are not needed as it will be removed in mmdet3.0 era, but we need to implement tests for our own custom modules. In addition, it might be good to have integration / e2e tests and documentation update. Not necessarily in this PR, though.

2023-10-19 06:31 UTC, goodsong81 commented on src/otx/algorithms/detection/configs/instance_segmentation/rtmdet_ins_tiny/template.yaml
> +  nncf: otx.algorithms.detection.adapters.mmdet.nncf.task.DetectionNNCFTask
We don't need to support NNCF QAT for new models. Let's remove this line.

2023-10-19 07:02 UTC, sungmanc reviewed
Thanks for the introducing nice architecture. 
I left 2 comments for this PR.

2023-10-19 07:02 UTC, sungmanc commented on src/otx/algorithms/detection/adapters/mmdet/models/assigners/dynamic_soft_label_assigner.py
> +# Copyright (c) OpenMMLab. All rights reserved.
@yunchu , is there no problem use this copyright?

2023-10-19 07:02 UTC, sungmanc commented on src/otx/algorithms/detection/configs/instance_segmentation/rtmdet_ins_tiny/data_pipeline.py
> +    dict(type="CachedMosaic", img_scale=img_size, pad_val=114.0, max_cached_images=20, random_pop=False),
This is the extreme case.

What would happen if there is no memory for `CachedMosaic` or `CachedMixUp`? It seems that it will raise an error if there are < 4 cached_images, is it safe to use?

2023-10-24 08:15 UTC, jaegukhyun approved these changes, later dismissed
Generally LGTM, I added some questions

2023-10-24 08:15 UTC, jaegukhyun commented on src/otx/algorithms/detection/adapters/mmdet/datasets/pipelines/transforms.py
Is this file going to remove when we migrate to mmdet3.x?

2023-10-24 08:15 UTC, jaegukhyun commented on src/otx/api/usecases/exportable_code/prediction_to_annotation_converter.py
Could you explain about this change? It seems affecting to all instance segmentation models

2023-10-26 07:53 UTC, yunchu commented on src/otx/algorithms/detection/adapters/mmdet/models/assigners/dynamic_soft_label_assigner.py
> +# Copyright (c) OpenMMLab. All rights reserved.
if the code was copied from the OpenMMLab without any modification it should keep the same header and it's better to left a comment about the original code URL.

2024-02-29 08:21 UTC, closed without merging