OTE_SDK. Increase code coverage label_schema.py, train_parameters.py
open-edge-platform/training_extensions pull request #760
Opened 2021-12-08 10:47 UTC by saltykox

Test list:
•	ote_sdk/ote_sdk/tests/entities/test_label_schema.py (renamed from ote_sdk/ote_sdk/tests/entities/test_label_schema_entity.py)
•	ote_sdk/ote_sdk/tests/entities/test_train_parameters.py

Task: CVS-72107

2021-12-08 10:48 UTC, saltykox commented
run ote_sdk tests

2021-12-08 12:04 UTC, saltykox commented
@LeonidBeynenson please review

2021-12-14 10:44 UTC, Ilya-Krylov requested changes

2021-12-14 10:44 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_train_parameters.py
> +        Test passes if attributes of TrainParameters class object are equal expected
```suggestion
        Test passes if attributes of TrainParameters class object are equal to expected
```

2021-12-14 10:44 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_train_parameters.py
> +        1. Check attributes of TrainParameters object initiated with default parameters
```suggestion
        1. Check attributes of TrainParameters object initialized with default parameters
```

2021-12-14 10:44 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_train_parameters.py
> +        2. Check attributes of TrainParameters object initiated with "resume", "update_progress" and "save_model"
```suggestion
        2. Check attributes of TrainParameters object initialized with "resume", "update_progress" and "save_model"
```

2021-12-14 10:44 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_train_parameters.py
> +        # Expected that save_model equal to function for default parameters TrainParameters object
```suggestion
        # Expected that save_model is equal to function for default parameters TrainParameters object
```

2021-12-14 10:44 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_label_schema.py
> +        assert rifle in threat_children
redundant

2021-12-14 10:44 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_label_schema.py
> +        Test passes if the LabelSchema and hierarchy are correctly represented
```suggestion
        Test passes if the LabelSchemaEntity and hierarchy are correctly represented
```

2021-12-14 10:44 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_label_schema.py
> +        1. Create LabelSchema with hierarchy
```suggestion
        1. Create LabelSchemaEntity with hierarchy
```

2021-12-14 10:44 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_label_schema.py
> +        1. Create LabelSchema with "Vegetation" exclusive group
```suggestion
        1. Create LabelSchemaEntity with "Vegetation" exclusive group
```

2021-12-14 10:44 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_label_schema.py
> +        Check that LabelSchema equality works correctly
```suggestion
        Check that LabelSchemaEntity equality works correctly
```

2021-12-14 10:44 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_label_schema.py
> +        LabelSchema instances
```suggestion
        LabelSchemaEntity  instances
```

2021-12-14 10:44 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_label_schema.py
> +        1. Test LabelSchema equality
```suggestion
        1. Test LabelSchemaEntity equality
```

2021-12-14 10:44 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_label_schema.py
> +        A simple Label Tree
```suggestion
        A simple LabelTree
```

2021-12-14 10:44 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_label_schema.py
> +        Test passes if LabelGroupType Enum class length is equal expected value and its elements have expected
```suggestion
        Test passes if LabelGroupType Enum class length is equal to expected value and its elements have expected
```

2021-12-14 10:44 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_label_schema.py
> +        "is_single_label" methods are equal expected
```suggestion
        "is_single_label" methods are equal to expected
```

2021-12-14 10:44 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_label_schema.py
> +        Test passes if LabelGraph object "directed" attribute and "num_labels" and "type" properties are equal expected
```suggestion
        Test passes if LabelGraph object "directed" attribute and "num_labels" and "type" properties are equal to expected
```

2021-12-14 10:57 UTC, saltykox commented on ote_sdk/ote_sdk/tests/entities/test_label_schema.py
> +        assert rifle in threat_children
Thanks, removed redundant assertion from test_label_tree

2021-12-14 12:32 UTC, Ilya-Krylov commented
run ote_sdk tests

2021-12-14 14:45 UTC, merged