[OTE_SDK_TESTS] Increase code coverage against entities classes part1
open-edge-platform/training_extensions pull request #788
Opened 2021-12-16 11:46 UTC by FyodorK

new file:   ote_sdk/ote_sdk/tests/entities/test_coordinate.py
	new file:   ote_sdk/ote_sdk/tests/entities/test_image.py
	new file:   ote_sdk/ote_sdk/tests/entities/test_media.py
	new file:   ote_sdk/ote_sdk/tests/entities/test_metadata.py

Getting rid from wrongly merged alien commits.

2021-12-23 12:17 UTC, Ilya-Krylov requested changes

2021-12-23 12:17 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_coordinate.py
> +        1. It raises TypeError in case of attempt of instantiation  with wrong number of parameters
```suggestion
        1. It raises TypeError in case of attempt of instantiation with wrong number of parameters
```

2021-12-23 12:17 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_coordinate.py
> +        2. Fields of instances initialized  with correct values
```suggestion
        2. Fields of instances initialized with correct values
```

2021-12-23 12:17 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_coordinate.py
> +        7. '==' method works is expected
```suggestion
        7. '==' method works as expected
```

2021-12-23 12:17 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_coordinate.py
> +        2. Initiate three class instances:
```suggestion
        2. Create three class instances:
```

2021-12-23 12:17 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_image.py
> +        Instances of Annotation class made against rectangle and
and what?

2021-12-23 12:17 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_image.py
> +        assert not np.array_equal(fp_instance.numpy, image)
what it should be equal to?

2021-12-23 12:17 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_image.py
> +        data0 = np.zeros(shape=(test_height, test_width, test_depth), dtype=float, order='C')
could you please fill these arrays randomly

2021-12-23 12:17 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_image.py
> +        for arr in fp_instance.roi_numpy(rect_annotation):
this `for` loop fully duplicates previous `for` loop

2021-12-23 12:17 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_image.py
> +        for arr in fp_instance.roi_numpy(rect_annotation):
no enough strict check, just compare arrays

2021-12-23 12:17 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_media.py
> +        1. Instantiate an instance of class
```suggestion
        1. Create an instance of class
```

2021-12-23 12:17 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_media.py
> +        1. Instantiate an instance of abstract class
```suggestion
        1. Create an instance of abstract class
```

2021-12-23 12:17 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_metadata.py
> +        Initiated instance of IMetadata class
```suggestion
        Initialized instance of IMetadata class
```

2021-12-23 12:17 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_metadata.py
> +        1. Initiated instance is instance of the class
```suggestion
        1. Initialized instance is instance of the class
```

2021-12-23 12:17 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_metadata.py
> +        2. Default value of field has expected value:  "typing.Union[str, NoneType]
```suggestion
        2. Default value of field has expected value:  "typing.Union[str, NoneType]"
```

2021-12-23 12:17 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_metadata.py
> +        1. Initiate IMetadata class instance
```suggestion
        1. Initialize IMetadata class instance
```

2021-12-23 12:17 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_metadata.py
> +        Initiated instance of FloatType enum class
please find and fix all "Initiated "

2021-12-23 13:01 UTC, Ilya-Krylov commented
run ote_sdk tests

2021-12-26 06:04 UTC, Ilya-Krylov commented
16:06:52  isort (ote_sdk)..........................................................Failed
16:06:52  - hook id: isort
16:06:52  - files were modified by this hook
16:06:52  
16:06:52  Fixing /home/jenkins/b/workspace/ote/precommit/ote_sdk_tests_runner/src/ote_sdk/ote_sdk/tests/entities/test_media.py
16:06:52  Fixing /home/jenkins/b/workspace/ote/precommit/ote_sdk_tests_runner/src/ote_sdk/ote_sdk/tests/entities/test_image.py
16:06:52  Fixing /home/jenkins/b/workspace/ote/precommit/ote_sdk_tests_runner/src/ote_sdk/ote_sdk/tests/entities/test_metadata.py
16:06:52  
16:06:52  isort (ote_cli|external).................................................Passed
16:06:52  black (ote_sdk|ote_cli)..................................................Failed
16:06:52  - hook id: black
16:06:52  - files were modified by this hook
16:06:52  
16:06:52  reformatted ote_sdk/ote_sdk/tests/entities/test_coordinate.py
16:06:52  reformatted ote_sdk/ote_sdk/tests/entities/test_media.py
16:06:52  reformatted ote_sdk/ote_sdk/tests/entities/test_image.py
16:06:52  reformatted ote_sdk/ote_sdk/tests/entities/test_metadata.py
16:06:52  All done! ✨ 🍰 ✨
16:06:52  4 files reformatted, 188 files left unchanged.
16:06:52  
16:06:53  black (rest).............................................................Passed
16:06:54  flake8...................................................................Passed
16:06:54  prettier.................................................................Passed
16:06:59  mypy (ote_sdk)...........................................................Passed
16:06:59  mypy (ote_cli)...........................................................Passed
16:07:00  mypy (external)..........................................................Passed
16:07:32  pylint...................................................................Passed
16:07:32  [Pipeline] }

2022-01-17 06:50 UTC, Ilya-Krylov commented
please make sure that your branch is up to date with target branch. There should not be so many files changed. The same for another your pr.

2022-01-21 05:22 UTC, Ilya-Krylov commented
run ote_sdk tests

2022-01-21 13:22 UTC, FyodorK commented
I've added a comment in internal JIRA ticket. Please take a look.

2022-01-26 08:42 UTC, Ilya-Krylov commented
@FyodorK  could you eventually get rid of 'initiated' and fix issues that make CI (this CI) red?

2022-01-26 09:52 UTC, FyodorK commented
run ote_sdk tests

2022-01-26 12:44 UTC, FyodorK commented
run ote_sdk tests

2022-01-26 13:03 UTC, FyodorK commented
run ote_sdk tests

2022-01-28 06:26 UTC, merged