[OTE_SDK_TESTS] Increase code coverage against entities classes part2
open-edge-platform/training_extensions pull request #789
Opened 2021-12-16 12:04 UTC by FyodorK

new file:   ote_sdk/ote_sdk/tests/entities/test_inference_parameters.py
	new file:   ote_sdk/ote_sdk/tests/entities/test_optimization_parameters.py
	new file:   ote_sdk/ote_sdk/tests/entities/test_subset.py

Getting rid from wrongly merged alien commits

2021-12-23 12:52 UTC, Ilya-Krylov requested changes

2021-12-23 12:52 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_inference_parameters.py
> +        1. Initiate InferenceParameters instance
find and fix all `initiate`

2021-12-23 12:52 UTC, Ilya-Krylov commented on ote_sdk/ote_sdk/tests/entities/test_subset.py
> +        __repr__ method return correct string
```suggestion
        __repr__ method returns correct string
```

2021-12-23 13:02 UTC, Ilya-Krylov commented
run ote_sdk tests

2021-12-26 06:06 UTC, Ilya-Krylov commented
16:05:30  isort (ote_sdk)..........................................................Failed
16:05:30  - hook id: isort
16:05:30  - files were modified by this hook
16:05:30  
16:05:30  Fixing /home/jenkins/b/workspace/ote/precommit/ote_sdk_tests_runner/src/ote_sdk/ote_sdk/tests/entities/test_optimization_parameters.py
16:05:30  Fixing /home/jenkins/b/workspace/ote/precommit/ote_sdk_tests_runner/src/ote_sdk/ote_sdk/tests/entities/test_inference_parameters.py
16:05:30  Fixing /home/jenkins/b/workspace/ote/precommit/ote_sdk_tests_runner/src/ote_sdk/ote_sdk/tests/entities/test_subset.py
16:05:30  
16:05:30  isort (ote_cli|external).................................................Passed
16:05:32  black (ote_sdk|ote_cli)..................................................Failed
16:05:32  - hook id: black
16:05:32  - files were modified by this hook
16:05:32  
16:05:32  reformatted ote_sdk/ote_sdk/tests/entities/test_inference_parameters.py
16:05:32  reformatted ote_sdk/ote_sdk/tests/entities/test_optimization_parameters.py
16:05:32  All done! ✨ 🍰 ✨
16:05:32  2 files reformatted, 189 files left unchanged.
16:05:32  
16:05:32  black (rest).............................................................Passed
16:05:34  flake8...................................................................Passed
16:05:35  prettier.................................................................Passed
16:05:39  mypy (ote_sdk)...........................................................Passed
16:05:39  mypy (ote_cli)...........................................................Passed
16:05:40  mypy (external)..........................................................Passed
16:06:19  pylint...................................................................Passed
16:06:19  [Pipeline] }
16:06:19  ERROR: script returned exit code 1

2022-01-21 05:23 UTC, Ilya-Krylov commented
run ote_sdk tests

2022-01-21 13:19 UTC, FyodorK commented
I've add a comment with url into internal JIRA ticket. Please take a look.

2022-01-26 13:05 UTC, FyodorK commented
run ote_sdk tests

2022-01-27 07:15 UTC, FyodorK commented
run ote_sdk tests

2022-01-28 06:27 UTC, merged