[MISC] Mammogram screening model
open-edge-platform/training_extensions pull request #901
Opened 2022-02-07 19:12 UTC by Rakshith2597

Submitting training module for A Two-Stage Multiple Instance Learning Framework for the Detection of Breast Cancer in Mammograms

Paper: [EMBC](https://ieeexplore.ieee.org/document/9176427)
Dataset used for this code repo: [Medical decathalon](https://ieee-dataport.org/documents/re-curated-breast-imaging-subset-ddsm-dataset-rbis-ddsm)

This is part of the project MIRIAD: Many Incarnations of Screening of Radiology for High Throughput Disease Screening via Multiple Instance Reinforcement Learning with Adversarial Deep Neural Networks, sponsored by INTEL TECHNOLOGY INDIA PVT. LTD.

Principal Investigators:
Dr Debdoot Sheet (PI), Dr Nirmalya Ghosh (Co-PI)
Department of Electrical Engineering
Indian Institute of Technology Kharagpur

Dr Ramanathan Sethuraman (Co-PI)
Intel Technology India Pvt. Ltd.

2022-02-08 05:25 UTC, Rakshith2597 commented
@morkovka1337 This one is ready for review.

2022-02-09 14:02 UTC, morkovka1337 requested changes
Overall it is good. A couple of general comments:
1. Please, delete commented code once you do not have need it anymore
2. I think, in the callable scripts (where you have `get_config` function call), it is reasonable to have an argument for the config file path. User can have more than two default configs.

2022-02-09 14:02 UTC, morkovka1337 commented on misc/pytorch_toolkit/mammogram_screening/init_venv.sh
> +fi
This is no longer needed if you use OpenVINO from the PyPi

2022-02-09 14:02 UTC, morkovka1337 commented on misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage1/inference_mass_localization.py
> +                    # print(img.shape)
please, delete commented code

2022-02-09 14:02 UTC, morkovka1337 commented on misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage1/inference_mass_localization.py
> +                    out = to_tensor(out).to(self.device) #.transpose(dim0=1, dim1=0)
please, delete commented code

2022-02-09 14:02 UTC, morkovka1337 commented on misc/pytorch_toolkit/mammogram_screening/mammogram_screening/train_utils/get_config.py
> +    config_path = os.path.join(root_path, 'configs')
a bit complicated way to get a config, I would suggest just pass a path to the config

2022-02-09 14:02 UTC, morkovka1337 commented on misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage1/inference_mass_localization.py
> +    config = get_config('inference')
Suggesting to change the behavior of `get_config` function (see corresponding comment in its definition) and add here an argument parser with parameters: path to a config and run type. Then you won't need commented parts below.

2022-02-09 14:02 UTC, morkovka1337 commented on misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage1/inference_mass_localization.py
> +                    # print(out.shape)
please, delete commented code

2022-02-09 14:02 UTC, morkovka1337 commented on misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage1/inference_mass_localization.py
> +                    out = to_tensor(out)#.squeeze(1)
commented code

2022-02-09 14:02 UTC, morkovka1337 commented on misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage1/train_stage1.py
> +    epochs = config['epochs']
same as above about argument parser.
Moreover, consider moving the train procedure into separate function and split the code into logical units. General rule of thumb for splitting function:
1. Function should not be bigger then 1 screen (upon certain exceptions, of course)
2. Function should do only one action according to its name

2022-02-09 14:02 UTC, morkovka1337 commented on misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage2/inference_stage2.py
> +    print(test_acc, auc)
Is it necessary to run all three types of model every time inference script is called? Consider adding run type argument and run only one model per script call.

2022-02-09 14:02 UTC, morkovka1337 commented on misc/pytorch_toolkit/mammogram_screening/mammogram_screening/train_utils/get_config.py
> +    """
looks like `action` annotation does not match the code below

2022-02-09 14:02 UTC, morkovka1337 commented on misc/pytorch_toolkit/mammogram_screening/mammogram_screening/train_utils/loss_functions.py
> +    return criterion(pred, target)
```suggestion

def ceLoss(pred, target):
    criterion = nn.CrossEntropyLoss()
    return criterion(pred, target)
```
since this variable is relevant only to a certain function, it should be moved into it

2022-02-09 14:02 UTC, morkovka1337 commented on misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage2/step3_get_patches.py
> +            return (x, y, w, h)
Consider adding iterations count to prevent (unlikely, of course, but anyway) endless loop.

2022-02-09 14:02 UTC, morkovka1337 commented on misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage2/step3_get_patches.py
> +def extract_bags(predictions):
Too long function, could you, please, split it into small separate units?

2022-02-09 14:02 UTC, morkovka1337 commented on misc/pytorch_toolkit/mammogram_screening/mammogram_screening/train_utils/train_function.py
> +        loss = 0.2*loss_bce + 0.8*loss_dice
consider setting loss weights at least as constants in this file, more preferable to have an opportunity to tune them in from the config file (e.g., you can have default values in the model class and read them from the config, if they are specified in it).

2022-02-15 15:02 UTC, nervana-ff commented
Can one of the admins verify this patch?

2022-03-15 12:43 UTC, morkovka1337 commented
Sorry for delayed reply, will review this week.

2022-03-18 13:55 UTC, morkovka1337 commented
run tests

2022-03-18 13:57 UTC, morkovka1337 commented
run misc tests

2022-03-21 06:57 UTC, morkovka1337 commented
@Rakshith2597, tests are running more than 2 days already. I am afraid, something could be wrong. How long does it take to run tests locally?

2022-03-21 09:31 UTC, Rakshith2597 commented
> @Rakshith2597, tests are running more than 2 days already. I am afraid, something could be wrong. How long does it take to run tests locally?

@morkovka1337 Locally it takes around 25-30mins (approx).

2022-03-23 07:48 UTC, morkovka1337 commented
run tests

2022-03-23 07:50 UTC, morkovka1337 commented
run misc tests

2022-03-23 13:55 UTC, morkovka1337 commented
Please, fix pylint issues:

```
11:01:31  + python3 tools/run_pylint.py
11:02:03  ERROR:root:pylint failed with code 22
11:02:03  ************* Module mammogram_screening.stage2.step3_get_patches
11:02:03  misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage2/step3_get_patches.py:95:20: W0612: Unused variable 'k' (unused-variable)
11:02:03  ************* Module mammogram_screening.stage2.inference_stage2
11:02:03  misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage2/inference_stage2.py:94:41: C0303: Trailing whitespace (trailing-whitespace)
11:02:03  ************* Module mammogram_screening.stage2.train_stage2
11:02:03  misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage2/train_stage2.py:16:13: E1120: No value for argument 'config_path' in function call (no-value-for-parameter)
11:02:03  ************* Module mammogram_screening.stage1.train_stage1
11:02:03  misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage1/train_stage1.py:16:21: W0621: Redefining name 'config' from outer scope (line 102) (redefined-outer-name)
11:02:03  misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage1/train_stage1.py:17:4: W0621: Redefining name 'epochs' from outer scope (line 103) (redefined-outer-name)
11:02:03  misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage1/train_stage1.py:21:4: W0621: Redefining name 'model_path' from outer scope (line 103) (redefined-outer-name)
11:02:03  misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage1/train_stage1.py:25:4: W0621: Redefining name 'device' from outer scope (line 103) (redefined-outer-name)
11:02:03  misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage1/train_stage1.py:34:4: W0621: Redefining name 'train_loader' from outer scope (line 103) (redefined-outer-name)
11:02:03  misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage1/train_stage1.py:37:4: W0621: Redefining name 'val_loader' from outer scope (line 103) (redefined-outer-name)
11:02:03  misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage1/train_stage1.py:39:4: W0621: Redefining name 'model' from outer scope (line 103) (redefined-outer-name)
11:02:03  misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage1/train_stage1.py:42:4: W0621: Redefining name 'optimizer' from outer scope (line 103) (redefined-outer-name)
11:02:03  misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage1/train_stage1.py:47:4: W0621: Redefining name 'scheduler' from outer scope (line 103) (redefined-outer-name)
11:02:03  misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage1/train_stage1.py:51:16: W0621: Redefining name 'epochs' from outer scope (line 103) (redefined-outer-name)
11:02:03  misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage1/train_stage1.py:51:24: W0621: Redefining name 'model' from outer scope (line 103) (redefined-outer-name)
11:02:03  misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage1/train_stage1.py:51:31: W0621: Redefining name 'train_loader' from outer scope (line 103) (redefined-outer-name)
11:02:03  misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage1/train_stage1.py:51:45: W0621: Redefining name 'optimizer' from outer scope (line 103) (redefined-outer-name)
11:02:03  misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage1/train_stage1.py:51:56: W0621: Redefining name 'device' from outer scope (line 103) (redefined-outer-name)
11:02:03  misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage1/train_stage1.py:51:64: W0621: Redefining name 'val_loader' from outer scope (line 103) (redefined-outer-name)
11:02:03  misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage1/train_stage1.py:51:76: W0621: Redefining name 'scheduler' from outer scope (line 103) (redefined-outer-name)
11:02:03  misc/pytorch_toolkit/mammogram_screening/mammogram_screening/stage1/train_stage1.py:51:87: W0621: Redefining name 'model_path' from outer scope (line 103) (redefined-outer-name)
11:02:03  ************* Module mammogram_screening.train_utils.models
11:02:03  misc/pytorch_toolkit/mammogram_screening/mammogram_screening/train_utils/models.py:95:27: E1101: Function 'input' has no 'size' member (no-member)
11:02:03  ************* Module mammogram_screening.train_utils.export
11:02:03  misc/pytorch_toolkit/mammogram_screening/mammogram_screening/train_utils/export.py:52:13: E1120: No value for argument 'config_path' in function call (no-value-for-parameter)
11:02:03  misc/pytorch_toolkit/mammogram_screening/mammogram_screening/train_utils/export.py:57:13: E1120: No value for argument 'config_path' in function call (no-value-for-parameter)
11:02:03  ************* Module mammogram_screening.train_utils.transforms
11:02:03  misc/pytorch_toolkit/mammogram_screening/mammogram_screening/train_utils/transforms.py:285:12: W0125: Using a conditional statement with a constant value (using-constant-test)
11:02:03  
11:02:03  -----------------------------------
11:02:03  Your code has been rated at 9.97/10
```

2022-04-07 07:55 UTC, Rakshith2597 commented
run tests

2022-04-07 07:56 UTC, Rakshith2597 commented
run misc tests

2022-04-08 14:06 UTC, morkovka1337 commented
Hi @Rakshith2597

Work on this pull request have to be paused from my side due to the temporal suspension of business of intel in Russia.

2022-05-02 16:20 UTC, ryanloney commented
@openvinotoolkit/ote-maintainers can you please review?

2022-05-03 05:26 UTC, goodsong81 commented
I couldn't have time to figure out how to deal with MISC PRs yet due to urgent release of v0.2.0.
Could you let me know where is the 'run tests / run misc tests' is running?
Link would also be OK.

2022-05-10 10:46 UTC, Rakshith2597 commented
Any updates on this?

2022-05-16 09:15 UTC, goodsong81 commented
There seem to be remaining pylint issues.
![image](https://user-images.githubusercontent.com/4629606/168557817-53a139a0-5f17-48fa-8142-884c55350e10.png)

And why don't you add some 'how to run' guide in your ReadMe.md to help others reproduce?
e.g.)
```console
$ ./init_venv.sh
$ ./mammogram_screening/stage1/train_stage1.py ...???
```

Finally, could you run unit tests locally and attach the screen capture here? It would replace CI tests temporarily.

2022-05-16 09:17 UTC, goodsong81 requested changes
Please refer to above comments.

2022-07-05 08:31 UTC, goodsong81 approved these changes
LGTM.

2022-07-05 08:32 UTC, merged